"""Precedent-log tests (issue #445) — the greenlight loop's learning half.

Three groups, mirroring the module's three pure layers:

- **parse/render** — the strict ndjson schema, every malformation loud with
  its line number, and the golden round-trip against the REAL committed seed
  (``telemetry/reeve-greenlights.ndjson``, the six stage-1 records): every
  line must parse and re-render byte-for-byte, so a hand-edited or
  schema-drifting seed fails here rather than shipping quietly.
- **derive** — the observer's rule: resolved + unrecorded threads yield
  exactly one record each, everything else yields none, and the reaction
  precedence (ledger row → verdict label → inline reply → honest none) and
  outcome shapes are pinned.
- **load** — the drafter's capped context: the most recent records reach the
  digest, records beyond the cap never do, replies are bounded, and an empty
  log renders the fresh-log placeholder rather than an error.
"""

import json
import pathlib

import pytest

from reeve import greenlights

REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
SEED = REPO_ROOT / "telemetry" / "reeve-greenlights.ndjson"


def _record(**overrides):
    """One minimal valid record, with ``overrides`` applied."""
    base = {
        "issue": 501,
        "verdict": "yes",
        "reasoning": "the parked scope is already bounded by the issue",
        "owner_reaction": "/decide approved (ship-it) by the-owner",
        "outcome": "closed by #512",
        "recorded_at": "2026-09-01T05:53:04Z",
    }
    base.update(overrides)
    return base


def _thread(number=501, **overrides):
    """One minimal gathered thread (``github.gather_greenlight_rounds`` shape)."""
    base = {
        "number": number,
        "title": "something parked",
        "state": "open",
        "labels": ["needs-decision"],
        "greenlight_verdict": "yes",
        "greenlight_reasoning": "GREENLIGHT: YES\nthe scope is bounded",
        "owner_replies": [],
        "closing_pr": None,
    }
    base.update(overrides)
    return base


# --- parse/render -------------------------------------------------------------


def test_seed_round_trips_byte_for_byte():
    """The golden pin: the committed seed parses and re-renders unchanged.

    The seed records the stage-1 round (#296) and was generated by
    ``render_line`` itself; if a hand edit or a schema change breaks that
    identity, this fails — the log's parse/render contract is not negotiable
    after records exist.
    """
    text = SEED.read_text(encoding="utf-8")
    records = greenlights.parse_log(text)
    assert len(records) == 6  # the stage-1 round: 201 202 230 265 267 269
    assert [r["issue"] for r in records] == [201, 202, 230, 265, 267, 269]
    # #269's marker predates the closed verdict set — recorded verbatim.
    assert records[-1]["verdict"] == "duplicate"
    for line, record in zip(text.splitlines(), records):
        assert greenlights.render_line(record) == line


def test_seed_records_the_stage1_stamp_and_outcomes():
    records = greenlights.parse_log(SEED.read_text(encoding="utf-8"))
    # recorded_at is the stage-1 results comment's own timestamp — the round's
    # ratification record, not today's.
    assert all(r["recorded_at"] == "2026-08-16T22:47:03Z" for r in records)
    by_issue = {r["issue"]: r for r in records}
    assert by_issue[230]["outcome"] == "merged #268 (f24c31a)"
    assert by_issue[267]["outcome"] == "merged #299"
    assert by_issue[269]["outcome"] == "closed as duplicate of #265"
    assert "autonomy-ok" in by_issue[201]["outcome"]
    assert "not armed" in by_issue[202]["outcome"]


def test_parse_log_skips_blank_lines_and_empty_is_clean():
    assert greenlights.parse_log("") == []
    assert greenlights.parse_log("\n\n  \n") == []
    text = greenlights.render_line(_record()) + "\n\n"
    assert len(greenlights.parse_log(text)) == 1


def _raw(**overrides):
    """One record serialized WITHOUT validation — the parse-side negative
    controls need lines ``render_line`` would itself refuse to emit."""
    record = _record()
    record.update(overrides)
    return json.dumps(record, ensure_ascii=False)


@pytest.mark.parametrize(
    "line, fragment",
    [
        ("{not json", "not valid JSON"),
        (_raw(issue=0), "positive integer"),
        (_raw(issue=True), "positive integer"),  # bool is not an issue number
        (_raw(verdict="maybe"), "'verdict'"),
        (_raw(reasoning="   "), "'reasoning'"),
        (_raw(owner_reaction=""), "'owner_reaction'"),
        (_raw(recorded_at="2026-09-01 05:53:04"), "'recorded_at'"),
    ],
)
def test_parse_log_is_loud_on_malformed_records(line, fragment):
    payload = greenlights.render_line(_record()) + "\n" + line + "\n"
    with pytest.raises(ValueError) as exc:
        greenlights.parse_log(payload)
    assert "telemetry/reeve-greenlights.ndjson:2" in str(exc.value)  # names the line
    assert fragment in str(exc.value)


def test_parse_log_names_the_missing_field():
    record = _record()
    del record["outcome"]
    with pytest.raises(ValueError) as exc:
        greenlights.parse_log(json.dumps(record))
    assert "missing ['outcome']" in str(exc.value)


def test_parse_log_rejects_a_non_object_line():
    with pytest.raises(ValueError) as exc:
        greenlights.parse_log("[1, 2, 3]")
    assert "must be a JSON object" in str(exc.value)


def test_parse_log_rejects_a_bad_stamp():
    # (kept separate from the parametrized table for one read: the stamp is the
    # field a hand-edit is most likely to typo)
    with pytest.raises(ValueError) as exc:
        greenlights.parse_log(_raw(recorded_at="2026/09/01"))
    assert "ISO-8601" in str(exc.value)


def test_render_line_emits_the_canonical_field_order():
    line = greenlights.render_line(_record())
    order = [line.index(f'"{field}"') for field in greenlights.FIELD_ORDER]
    assert order == sorted(order)


# --- the ledger read ----------------------------------------------------------


def test_parse_ledger_reads_rows_and_skips_comments():
    text = (
        "# the audit trail (docs/decision-gate.md)\n"
        "\n"
        "ship-it | approved | #501 | the-owner | 2026-09-01T06:00:00Z\n"
        "hold-it | rejected | #502 | the-owner | 2026-09-01T06:30:00Z\n"
    )
    rows = greenlights.parse_ledger(text)
    assert [r["issue"] for r in rows] == [501, 502]
    assert rows[0]["verdict"] == "approved"
    assert rows[1]["id"] == "hold-it"


@pytest.mark.parametrize(
    "row",
    [
        "ship-it | approved | 501 | the-owner | 2026-09-01T06:00:00Z",  # no # on the issue
        "ship-it | maybe | #501 | the-owner | 2026-09-01T06:00:00Z",   # not a verdict
        "ship-it | approved | #501 | | 2026-09-01T06:00:00Z",          # no login
        "ship-it | approved | #501 | the-owner | yesterday",            # not a stamp
        "only | three | fields",                                        # wrong arity
    ],
)
def test_parse_ledger_is_loud_on_malformed_rows(row):
    with pytest.raises(ValueError) as exc:
        greenlights.parse_ledger("good | approved | #500 | o | 2026-09-01T06:00:00Z\n" + row + "\n")
    assert ":2:" in str(exc.value)


def test_ledger_reaction_prefers_the_newest_row():
    rows = greenlights.parse_ledger(
        "first | rejected | #501 | o | 2026-09-01T06:00:00Z\n"
        "second | approved | #501 | o | 2026-09-01T07:00:00Z\n"
    )
    assert greenlights.ledger_reaction(rows, 501) == "/decide approved (second) by o"
    assert greenlights.ledger_reaction(rows, 999) is None


# --- derive (the observer's rule) ----------------------------------------------


def test_derive_records_one_per_newly_resolved_round():
    fresh = greenlights.derive_records(
        [
            _thread(501, state="closed", closing_pr=512),
            _thread(502),  # still parked — open, no verdict label
        ],
        recorded_issues=[],
        now="2026-09-02T05:53:04Z",
    )
    assert [r["issue"] for r in fresh] == [501]
    greenlights.validate_record(fresh[0])  # well-formed by the log's own schema
    assert fresh[0]["recorded_at"] == "2026-09-02T05:53:04Z"
    assert fresh[0]["verdict"] == "yes"


def test_derive_records_is_idempotent_against_the_log():
    fresh = greenlights.derive_records(
        [_thread(501, state="closed")],
        recorded_issues=[501],
        now="2026-09-02T05:53:04Z",
    )
    assert fresh == []  # re-observing a recorded round appends nothing


def test_derive_records_ignores_open_unresolved_threads():
    assert (
        greenlights.derive_records(
            [_thread(502)], recorded_issues=[], now="2026-09-02T05:53:04Z"
        )
        == []
    )


def test_derive_records_accepts_a_label_flip_without_a_close():
    # decide.yml's verdict labels resolve the gate while the thread stays open.
    fresh = greenlights.derive_records(
        [_thread(501, labels=["needs-decision", "decision-approved"])],
        recorded_issues=[],
        now="2026-09-02T05:53:04Z",
    )
    assert [r["issue"] for r in fresh] == [501]
    assert fresh[0]["outcome"] == "approved — follow-through pending"


def test_derive_records_outcome_shapes():
    cases = [
        (_thread(501, state="closed", closing_pr=512), "closed by #512"),
        (_thread(501, state="closed"), "closed"),
        (_thread(501, labels=["decision-approved"]), "approved — follow-through pending"),
        (_thread(501, labels=["decision-rejected"]), "rejected — follow-through pending"),
    ]
    for thread, want in cases:
        records = greenlights.derive_records([thread], [], now="2026-09-02T05:53:04Z")
        assert records[0]["outcome"] == want


def test_derive_records_reaction_precedence():
    ledger = {"ledger_reaction": "/decide approved (x) by o"}
    label = {"labels": ["decision-approved"]}
    reply = {"owner_replies": [{"author": "o", "text": "push it through"}]}
    nothing = {}
    for thread_overrides, want in [
        ({**ledger, **reply}, "/decide approved (x) by o"),        # the ledger row wins
        ({**label, **reply}, "approved (decision-approved label"),  # then the label
        (reply, "inline owner reply by o: push it through"),        # then the reply
        (nothing, "none observed"),                                 # then the honest none
    ]:
        records = greenlights.derive_records(
            [_thread(501, state="closed", **thread_overrides)],
            [],
            now="2026-09-02T05:53:04Z",
        )
        assert records[0]["owner_reaction"].startswith(want)


def test_derive_records_digests_long_reasoning_at_a_word_boundary():
    long_reasoning = "word " * 100
    records = greenlights.derive_records(
        [_thread(501, state="closed", greenlight_reasoning=long_reasoning)],
        [],
        now="2026-09-02T05:53:04Z",
    )
    reasoning = records[0]["reasoning"]
    assert len(reasoning) <= greenlights._REASONING_LIMIT
    assert reasoning.endswith("…")
    assert reasoning.split("…")[0].split()[-1] in long_reasoning.split()  # cut at a word


def test_derive_records_sorts_issue_ascending_and_dedupes():
    fresh = greenlights.derive_records(
        [
            _thread(503, state="closed"),
            _thread(501, state="closed"),
            _thread(501, state="closed"),  # a duplicated gather entry
        ],
        recorded_issues=[],
        now="2026-09-02T05:53:04Z",
    )
    assert [r["issue"] for r in fresh] == [501, 503]


def test_append_records_splices_after_the_existing_bytes():
    existing = greenlights.render_line(_record(issue=500)) + "\n"
    fresh = greenlights.derive_records(
        [_thread(501, state="closed")], [], now="2026-09-02T05:53:04Z"
    )
    updated = greenlights.append_records(existing, fresh)
    assert updated.startswith(existing)
    records = greenlights.parse_log(updated)
    assert [r["issue"] for r in records] == [500, 501]


def test_append_records_repairs_a_missing_final_newline():
    lone = greenlights.render_line(_record(issue=500))
    assert greenlights.append_records(lone, []) == lone  # nothing to append, no repair
    fresh = greenlights.derive_records(
        [_thread(501, state="closed")], [], now="2026-09-02T05:53:04Z"
    )
    updated = greenlights.append_records(lone, fresh)
    assert updated.count("\n") == 2  # the repaired separator + the record's own
    assert [r["issue"] for r in greenlights.parse_log(updated)] == [500, 501]


# --- load (the drafter's capped context) ----------------------------------------


def test_context_digest_carries_the_seed():
    records = greenlights.parse_log(SEED.read_text(encoding="utf-8"))
    digest = greenlights.context_digest(records, {}, cap=6)
    assert "most recent 6, capped at 6" in digest
    for issue in (201, 269):
        assert f"#{issue} ·" in digest
    # the stage-1 routing lesson is one of the seeds the drafter should read
    assert "closed as duplicate of #265" in digest


def test_context_digest_drops_records_beyond_the_cap():
    records = [_record(issue=500 + i) for i in range(8)]
    digest = greenlights.context_digest(records, {}, cap=3)
    assert "most recent 3, capped at 3" in digest
    for issue in (500, 501, 502, 503, 504):  # below the newest three
        assert f"#{issue} ·" not in digest
    for issue in (505, 506, 507):  # the newest three, newest first
        assert f"#{issue} ·" in digest


def test_context_digest_binds_replies_to_their_threads_only():
    records = [_record(issue=501), _record(issue=502)]
    replies = {501: [{"author": "o", "text": "push it through"}]}
    digest = greenlights.context_digest(records, replies, cap=6)
    assert "o on #501: push it through" in digest
    assert "#502:" not in digest.split("Inline owner replies", 1)[1]


def test_context_digest_bounds_replies_per_thread():
    replies = {
        501: [
            {"author": "o", "text": f"reply {i}"} for i in range(5)
        ]
    }
    digest = greenlights.context_digest([_record(issue=501)], replies, cap=6)
    assert "reply 0" in digest and "reply 1" in digest
    assert "reply 2" not in digest  # _REPLIES_PER_THREAD = 2


def test_context_digest_frames_replies_as_evidence_not_instructions():
    digest = greenlights.context_digest(
        [_record(issue=501)], {501: [{"author": "o", "text": "yes"}]}, cap=6
    )
    assert "never instructions" in digest


def test_context_digest_empty_log_is_the_fresh_placeholder():
    digest = greenlights.context_digest([], {}, cap=6)
    assert "no precedent records yet" in digest
    assert "charter alone" in digest
