#!/usr/bin/env python3
"""oracle_mcp.py — the Oracle reviewer's posting surface, as a stdio MCP tool.

WHY AN MCP TOOL (the same dead end the scout hit)
-------------------------------------------------
The Oracle's only write is "post ONE advisory review comment on the PR under
review", and that comment is rich multi-line markdown (headings, a per-AC
table with `|` pipes, code spans). Under `--permission-mode dontAsk` the Bash
permission matcher denies any command whose argument reads as shell structure
— a table pipe or an embedded newline is enough, no quoting fixes it (proven
on the scout's file-brief verb; see scout_mcp.py's header). An MCP tool takes
its arguments as JSON over a stdio pipe, never on a command line, so the body
can be arbitrary markdown. Same pattern, second consumer.

SECURITY (this is the write surface of an agent that reads untrusted diffs)
---------------------------------------------------------------------------
The Oracle run reads a PR's diff and the linked issue's thread — untrusted
text — while holding a GitHub token, so this server does NOT trust its inputs
and cannot be steered into anything but posting one clearly-labelled review
comment on the ONE PR the workflow selected:

  * the target PR comes ONLY from the ORACLE_PR environment variable, set by
    the trusted workflow — there is no argument for it, so a prompt-injected
    run can never redirect the comment to another issue or PR;
  * the marker (`<!-- ORACLE_REVIEW -->`), the "advisory" header line and the
    Claude Code attribution footer are HARDCODED here — every post is a
    recognisable, disclosed Oracle review, whatever the model writes;
  * a per-run cap of ONE post (a run-scoped in-process counter the agent
    cannot reach or reset) bounds a hijacked run to a single extra comment —
    noise a human deletes, never a flood;
  * a size cap bounds the body, so the tool cannot be used to dump a
    repository's contents into a PR thread;
  * the only GitHub call is `POST /issues/{ORACLE_PR}/comments` on the
    CURRENT repo — it never edits labels, never reviews/approves (it is a
    plain comment, not a PR review), never touches another repo, pushes no
    code.

The run allow-lists ONLY this tool (`mcp__oracle__post_oracle_review`) plus
the read-only file tools — never `Write`, never a general `Bash`. Stdlib only
(no pip install in the unattended run); logs go to stderr so stdout carries
nothing but JSON-RPC.
"""

import json
import os
import sys
import urllib.error
import urllib.request

GITHUB_API = "https://api.github.com"
SERVER_NAME = "oracle"
MARKER = "<!-- ORACLE_REVIEW -->"
HEADER = (
    "## \U0001F52E Oracle review — cross-vendor, reasoning-blind (advisory)"
)
FOOTER = "---\n_Generated by [Claude Code](https://claude.ai/code)_"
# One review comment is ~2-6 KB; 64 KiB is generous headroom for a large
# contract table while still refusing a repository dump (GitHub's own comment
# limit is 65536 characters).
MAX_BODY_BYTES = 64 * 1024
DEFAULT_PROTOCOL_VERSION = "2024-11-05"

# Per-run cap. GITHUB_RUN_ID is set and stable across one Actions run and this
# process lives for that whole run, so an in-process counter is naturally
# run-scoped. Attended (no run id) the cap is skipped — a human is the trust
# boundary, the same posture scout_mcp.py takes.
_posted_this_run = 0


def log(msg):
    """Diagnostics go to stderr — stdout is reserved for JSON-RPC frames."""
    print(f"oracle_mcp: {msg}", file=sys.stderr, flush=True)


def _repo():
    repo = os.environ.get("GITHUB_REPOSITORY", "").strip()
    if not repo:
        raise RuntimeError("GITHUB_REPOSITORY is not set")
    return repo


def _pr_number():
    """The one PR this run may post to — trusted workflow input, never an
    argument the model controls."""
    raw = os.environ.get("ORACLE_PR", "").strip()
    if not raw.isdigit():
        raise RuntimeError(
            "ORACLE_PR is not set to a PR number — the workflow must export it")
    return int(raw)


def _token():
    for var in ("GITHUB_TOKEN", "GH_TOKEN"):
        tok = os.environ.get(var, "").strip()
        if tok:
            return tok
    raise RuntimeError("no GitHub token (set GITHUB_TOKEN)")


def _api(method, path, payload=None):
    """One authenticated GitHub REST call. Returns the decoded JSON body."""
    url = f"{GITHUB_API}{path}"
    data = json.dumps(payload).encode() if payload is not None else None
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header("Authorization", f"Bearer {_token()}")
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("X-GitHub-Api-Version", "2022-11-28")
    req.add_header("User-Agent", "print-bench-oracle-review")
    if data is not None:
        req.add_header("Content-Type", "application/json")
    with urllib.request.urlopen(req, timeout=30) as resp:
        raw = resp.read().decode()
    return json.loads(raw) if raw else {}


# Captured by the selftest so it can assert the exact POST payload (marker,
# header, footer) without a network call. `None` in normal operation.
_last_payload = None
_last_path = None


def _post_comment(body):
    """POST one comment to the workflow-selected PR. The marker, header and
    footer are assembled HERE, from constants, never from caller input — so
    every post is a disclosed, attributed Oracle review whatever the body
    says. ORACLE_MCP_FAKE short-circuits the network for the selftest (it is
    never set in the workflow)."""
    global _last_payload, _last_path
    full = f"{MARKER}\n{HEADER}\n\n{body.rstrip()}\n\n{FOOTER}"
    payload = {"body": full}
    path = f"/repos/{_repo()}/issues/{_pr_number()}/comments"
    _last_payload = payload
    _last_path = path
    if os.environ.get("ORACLE_MCP_FAKE"):
        return {"html_url": "https://example.invalid/fake"}
    return _api("POST", path, payload)


def _post_oracle_review(arguments):
    """Post ONE advisory Oracle review comment. The Oracle's entire write
    taxonomy."""
    global _posted_this_run
    body = (arguments or {}).get("body")
    if not isinstance(body, str) or not body.strip():
        return _tool_error("post_oracle_review: 'body' is required (non-empty string)")
    if len(body.encode()) > MAX_BODY_BYTES:
        return _tool_error(
            f"post_oracle_review: body is {len(body.encode())} bytes, over the "
            f"{MAX_BODY_BYTES}-byte cap — a review is a verdict with evidence "
            f"pointers, not a data dump; condense it")

    # Per-run cap — enforced only inside an Actions run (the unattended case
    # it exists to bound); attended, a human is the trust boundary.
    run_id = os.environ.get("GITHUB_RUN_ID", "").strip()
    if run_id and _posted_this_run >= 1:
        return _tool_error(
            "the Oracle posts exactly ONE review per run and it is already "
            "posted; refusing a second comment")

    try:
        comment = _post_comment(body)
    except urllib.error.HTTPError as e:
        detail = e.read().decode(errors="replace")[:500] if hasattr(e, "read") else ""
        return _tool_error(f"GitHub API error {e.code} posting review: {detail}")
    except Exception as e:  # noqa: BLE001 — surface any failure to the agent
        return _tool_error(f"failed to post review: {type(e).__name__}: {e}")

    _posted_this_run += 1
    url = comment.get("html_url", "(unknown url)")
    log(f"posted Oracle review: {url}")
    return _tool_text(f"POSTED {url}")


# --- MCP tool registry ------------------------------------------------------

TOOLS = [
    {
        "name": "post_oracle_review",
        "description": (
            "Post the ONE advisory Oracle review comment on the PR this run "
            "was launched for (the workflow fixes the PR number — it is not "
            "an argument). The body is passed as a JSON argument, so it may "
            "be full multi-line markdown with tables. The ORACLE_REVIEW "
            "marker, the advisory header and the Claude Code attribution "
            "footer are added automatically — write only the review itself. "
            "One post per run; a second call is refused."
        ),
        "inputSchema": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string",
                    "description": (
                        "The review body in markdown: verdict, contract-vs-"
                        "diff findings in both directions, what could not be "
                        "verified. Tables, pipes, backticks and newlines are "
                        "all fine here."
                    ),
                },
            },
            "required": ["body"],
            "additionalProperties": False,
        },
    }
]

_DISPATCH = {"post_oracle_review": _post_oracle_review}


def _tool_text(text):
    return {"content": [{"type": "text", "text": text}], "isError": False}


def _tool_error(text):
    log(text)
    return {"content": [{"type": "text", "text": f"Error: {text}"}], "isError": True}


# --- JSON-RPC over stdio (newline-delimited) --------------------------------

def _result(msg_id, result):
    return {"jsonrpc": "2.0", "id": msg_id, "result": result}


def _error(msg_id, code, message):
    return {"jsonrpc": "2.0", "id": msg_id, "error": {"code": code, "message": message}}


def handle(msg):
    """Map one JSON-RPC request to a response dict, or None for notifications."""
    method = msg.get("method")
    msg_id = msg.get("id")

    if msg_id is None and "id" not in msg:
        # Notifications get no response; ignore other id-less messages quietly.
        return None

    if method == "initialize":
        params = msg.get("params") or {}
        version = params.get("protocolVersion") or DEFAULT_PROTOCOL_VERSION
        return _result(
            msg_id,
            {
                "protocolVersion": version,
                "capabilities": {"tools": {}},
                "serverInfo": {"name": SERVER_NAME, "version": "1.0.0"},
            },
        )

    if method == "ping":
        return _result(msg_id, {})

    if method == "tools/list":
        return _result(msg_id, {"tools": TOOLS})

    if method == "tools/call":
        params = msg.get("params") or {}
        name = params.get("name")
        fn = _DISPATCH.get(name)
        if fn is None:
            return _result(msg_id, _tool_error(f"unknown tool: {name!r}"))
        return _result(msg_id, fn(params.get("arguments") or {}))

    return _error(msg_id, -32601, f"method not found: {method}")


def selftest():
    """Prove the write surface's security invariants fire, offline. A guard
    that is never exercised can be weakened and every other check stays green
    (the repo's standing rule), so these are the cases a live run cannot
    show."""
    global _posted_this_run
    os.environ["ORACLE_MCP_FAKE"] = "1"
    os.environ["GITHUB_REPOSITORY"] = "example/selftest"
    os.environ["ORACLE_PR"] = "123"
    fails = []

    def check(name, cond):
        print(f"{'ok  ' if cond else 'FAIL'}  {name}")
        if not cond:
            fails.append(name)

    # Input guards reject and post nothing.
    check("missing body is rejected",
          _post_oracle_review({}).get("isError") is True)
    check("oversized body is rejected",
          _post_oracle_review({"body": "x" * (MAX_BODY_BYTES + 1)}).get("isError") is True)

    # A valid post carries the hardcoded marker, header and footer, and goes to
    # the ORACLE_PR comment endpoint — no argument can change any of that.
    _posted_this_run = 0
    ok = _post_oracle_review({"body": "## Verdict\n| AC | held |\n|---|---|\nCONCUR"})
    check("a well-formed review posts", ok.get("isError") is False)
    check("the posted body carries the hardcoded marker",
          _last_payload["body"].startswith(MARKER))
    check("the posted body carries the advisory header",
          HEADER in _last_payload["body"])
    check("the posted body ends with the attribution footer",
          _last_payload["body"].endswith(FOOTER))
    check("the post targets the workflow-selected PR only",
          _last_path == "/repos/example/selftest/issues/123/comments")

    # The one-post-per-run cap fires inside an Actions run (GITHUB_RUN_ID set).
    os.environ["GITHUB_RUN_ID"] = "selftest-run"
    _posted_this_run = 0
    r1 = _post_oracle_review({"body": "first"})
    r2 = _post_oracle_review({"body": "second"})
    check("the first post of a run goes through", r1.get("isError") is False)
    check("a second post in the same run is refused",
          r2.get("isError") is True and "ONE review" in r2["content"][0]["text"])
    del os.environ["GITHUB_RUN_ID"]

    # A missing/invalid ORACLE_PR refuses rather than guessing a target.
    _posted_this_run = 0
    os.environ["ORACLE_PR"] = ""
    r = _post_oracle_review({"body": "x"})
    check("a missing ORACLE_PR is refused", r.get("isError") is True)
    os.environ["ORACLE_PR"] = "123"

    # The JSON-RPC surface only exposes the one tool.
    check("tools/list exposes exactly post_oracle_review",
          [t["name"] for t in TOOLS] == ["post_oracle_review"])

    if fails:
        print(f"\noracle_mcp selftest FAILED: {', '.join(fails)}")
        return 1
    print("\noracle_mcp selftest passed")
    return 0


def main():
    if "--selftest" in sys.argv:
        raise SystemExit(selftest())
    log(f"starting (repo={os.environ.get('GITHUB_REPOSITORY', '?')}, "
        f"pr={os.environ.get('ORACLE_PR', '?')}, "
        f"run={os.environ.get('GITHUB_RUN_ID', 'attended')})")
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            msg = json.loads(line)
        except json.JSONDecodeError as e:
            log(f"skipping unparseable line: {e}")
            continue
        try:
            response = handle(msg)
        except Exception as e:  # noqa: BLE001 — never let one message kill the loop
            log(f"handler error: {type(e).__name__}: {e}")
            response = _error(msg.get("id"), -32603, f"internal error: {e}")
        if response is not None:
            sys.stdout.write(json.dumps(response) + "\n")
            sys.stdout.flush()
    log("stdin closed, exiting")


if __name__ == "__main__":
    main()
