#!/usr/bin/env python3
"""oracle_mcp.py — the Oracle reviewer's posting surface, as a stdio MCP tool.

WHY AN MCP TOOL (the same dead end the scout hit)
-------------------------------------------------
The Oracle's only write is "post ONE advisory review comment on the PR under
review", and that comment is rich multi-line markdown (headings, a per-AC
table with `|` pipes, code spans). Under `--permission-mode dontAsk` the Bash
permission matcher denies any command whose argument reads as shell structure
— a table pipe or an embedded newline is enough, no quoting fixes it (proven
on the scout's file-brief verb; see scout_mcp.py's header). An MCP tool takes
its arguments as JSON over a stdio pipe, never on a command line, so the body
can be arbitrary markdown. Same pattern, second consumer.

SECURITY (this is the write surface of an agent that reads untrusted diffs)
---------------------------------------------------------------------------
The Oracle run reads a PR's diff and the linked issue's thread — untrusted
text — while holding a GitHub token, so this server does NOT trust its inputs
and cannot be steered into anything but posting one clearly-labelled review
comment on the ONE PR the workflow selected:

  * the target PR comes ONLY from the ORACLE_PR environment variable, set by
    the trusted workflow — there is no argument for it, so a prompt-injected
    run can never redirect the comment to another issue or PR;
  * the marker (`<!-- ORACLE_REVIEW -->`), the "advisory" header line and the
    Claude Code attribution footer are HARDCODED here — every post is a
    recognisable, disclosed Oracle review, whatever the model writes;
  * a per-run cap of ONE post bounds a hijacked run to a single extra
    comment — noise a human deletes, never a flood. It is counted in a state
    file every link step of the chain walk shares (`ORACLE_CAP_STATE`, the
    scout's #565 mechanism and the reeve.yml `REEVE_GREENLIGHT_STATE`
    pattern), so the bound spans the whole walk and not one server process;
    the agent can neither set env vars nor write files, so it cannot reach or
    reset the count;
  * a size cap bounds the body, so the tool cannot be used to dump a
    repository's contents into a PR thread;
  * the only GitHub call is `POST /issues/{ORACLE_PR}/comments` on the
    CURRENT repo — it never edits labels, never reviews/approves (it is a
    plain comment, not a PR review), never touches another repo, pushes no
    code.

The run allow-lists ONLY this tool (`mcp__oracle__post_oracle_review`) plus
the read-only file tools — never `Write`, never a general `Bash`. Stdlib only
(no pip install in the unattended run); logs go to stderr so stdout carries
nothing but JSON-RPC.
"""

import json
import os
import subprocess
import sys
import tempfile
import urllib.error
import urllib.request
from datetime import datetime, timezone

GITHUB_API = "https://api.github.com"
SERVER_NAME = "oracle"
MARKER = "<!-- ORACLE_REVIEW -->"
HEADER = (
    "## \U0001F52E Oracle review — cross-vendor, reasoning-blind (advisory)"
)
FOOTER = "---\n_Generated by [Claude Code](https://claude.ai/code)_"
# One review comment is ~2-6 KB; 64 KiB is generous headroom for a large
# contract table while still refusing a repository dump (GitHub's own comment
# limit is 65536 characters).
MAX_BODY_BYTES = 64 * 1024
DEFAULT_PROTOCOL_VERSION = "2024-11-05"

# The review cap: exactly ONE post per run. Deliberately not an env knob —
# "one advisory review per PR event" is the Oracle's contract, not a tunable.
MAX_POSTS_PER_RUN = 1

# --- The walk-spanning review cap (the #549 class, Oracle sibling) -----------
#
# oracle.yml walks its opposite-vendor chain one claude-code-action step per
# link (3 Anthropic links, 4 GLM links), and each step launches this server as
# a FRESH process — so anything in-process restarts at link N+1. An in-process
# counter therefore caps ONE LINK, not the run: a link that posts its review
# and then ends without `outcome == success` (agent error, step timeout) hands
# the next link a fresh counter with the same prompt, so one run could land a
# second "exactly ONE" Oracle review per remaining link. The count must live
# where every link can see it: a state file the workflow names via
# ORACLE_CAP_STATE, one path shared by every link step of the job (the
# reeve.yml REEVE_GREENLIGHT_STATE precedent). runner.temp is fresh per job, so
# the file is run-scoped and never persists — every PR event still gets its
# one review.
#
# Lifted from scout_mcp.py's #565 reference implementation per that file's
# SIBLING ADOPTION note — the mechanism, not just the idea: the functions below
# are self-contained (stdlib only, no scout-specific coupling), adopted under
# this server's own env-var name. The cap-state wiring drift guard
# (tools/model-registry/tests/test_cap_state_wiring.py) reads CAP_STATE_ENV
# from this file and fails pre-merge if a link step that launches this server
# does not set it, or sets a different path than its sibling links.
CAP_STATE_ENV = "ORACLE_CAP_STATE"


def _cap_state_path():
    """The shared state-file path for this run, or None attended.

    Attended (no GITHUB_RUN_ID) the cap is skipped entirely — a human is the
    trust boundary — so no state file is required. Unattended the path comes
    from the env var the workflow sets; an empty value is returned as-is so the
    caller can refuse: posting on without it would silently fall back to
    per-process counting, which is exactly the per-link reset this mechanism
    exists to kill.
    """
    if not os.environ.get("GITHUB_RUN_ID", "").strip():
        return None
    return os.environ.get(CAP_STATE_ENV, "").strip()


def _cap_state_count(path):
    """How many reviews this run has already posted, per the shared state file.

    One JSON record per successful post, so the count is the number of
    non-empty lines; an absent file is a run that has posted nothing yet (the
    first successful post creates it). Any other read failure raises — an
    unreadable state must refuse, never count as zero.
    """
    try:
        with open(path, encoding="utf-8") as fh:
            return sum(1 for line in fh if line.strip())
    except FileNotFoundError:
        return 0
    except OSError as e:
        raise RuntimeError(f"cannot read {CAP_STATE_ENV} file {path}: {e}") from e


def _cap_state_record(path, pr, url):
    """Append ONE record — only ever AFTER a successful post, so refused and
    failed attempts never consume the cap (the greenlight wrapper's rule). The
    record doubles as the audit trail of what a link that later died posted."""
    rec = {"pr": pr, "url": url,
           "posted_at": datetime.now(timezone.utc).isoformat()}
    with open(path, "a", encoding="utf-8") as fh:
        fh.write(json.dumps(rec) + "\n")


def _cap_state_ensure_appendable(path):
    """Fail-closed preflight: the state path must be appendable BEFORE a
    GitHub write. Create the file if absent (zero posted so far); refuse if
    the path is readable-but-not-appendable or its directory is missing —
    otherwise a successful post that can't be recorded lets a later link post
    a second review."""
    try:
        with open(path, "a", encoding="utf-8"):
            pass
    except OSError as e:
        raise RuntimeError(
            f"cannot append to {CAP_STATE_ENV} file {path}: {e}"
        ) from e


def log(msg):
    """Diagnostics go to stderr — stdout is reserved for JSON-RPC frames."""
    print(f"oracle_mcp: {msg}", file=sys.stderr, flush=True)


def _repo():
    repo = os.environ.get("GITHUB_REPOSITORY", "").strip()
    if not repo:
        raise RuntimeError("GITHUB_REPOSITORY is not set")
    return repo


def _pr_number():
    """The one PR this run may post to — trusted workflow input, never an
    argument the model controls."""
    raw = os.environ.get("ORACLE_PR", "").strip()
    if not raw.isdigit():
        raise RuntimeError(
            "ORACLE_PR is not set to a PR number — the workflow must export it")
    return int(raw)


def _token():
    for var in ("GITHUB_TOKEN", "GH_TOKEN"):
        tok = os.environ.get(var, "").strip()
        if tok:
            return tok
    raise RuntimeError("no GitHub token (set GITHUB_TOKEN)")


def _api(method, path, payload=None):
    """One authenticated GitHub REST call. Returns the decoded JSON body."""
    url = f"{GITHUB_API}{path}"
    data = json.dumps(payload).encode() if payload is not None else None
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header("Authorization", f"Bearer {_token()}")
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("X-GitHub-Api-Version", "2022-11-28")
    req.add_header("User-Agent", "print-bench-oracle-review")
    if data is not None:
        req.add_header("Content-Type", "application/json")
    with urllib.request.urlopen(req, timeout=30) as resp:
        raw = resp.read().decode()
    return json.loads(raw) if raw else {}


# Captured by the selftest so it can assert the exact POST payload (marker,
# header, footer) without a network call. `None` in normal operation.
_last_payload = None
_last_path = None


def _post_comment(body):
    """POST one comment to the workflow-selected PR. The marker, header and
    footer are assembled HERE, from constants, never from caller input — so
    every post is a disclosed, attributed Oracle review whatever the body
    says. ORACLE_MCP_FAKE short-circuits the network for the selftest (it is
    never set in the workflow)."""
    global _last_payload, _last_path
    full = f"{MARKER}\n{HEADER}\n\n{body.rstrip()}\n\n{FOOTER}"
    payload = {"body": full}
    path = f"/repos/{_repo()}/issues/{_pr_number()}/comments"
    _last_payload = payload
    _last_path = path
    if os.environ.get("ORACLE_MCP_FAKE"):
        return {"html_url": "https://example.invalid/fake"}
    return _api("POST", path, payload)


def _post_oracle_review(arguments):
    """Post ONE advisory Oracle review comment. The Oracle's entire write
    taxonomy."""
    body = (arguments or {}).get("body")
    if not isinstance(body, str) or not body.strip():
        return _tool_error("post_oracle_review: 'body' is required (non-empty string)")
    if len(body.encode()) > MAX_BODY_BYTES:
        return _tool_error(
            f"post_oracle_review: body is {len(body.encode())} bytes, over the "
            f"{MAX_BODY_BYTES}-byte cap — a review is a verdict with evidence "
            f"pointers, not a data dump; condense it")

    # Per-run cap — enforced only inside an Actions run (the unattended case
    # it exists to bound); attended, a human is the trust boundary. The count
    # is read from the shared state file so it spans the whole chain walk,
    # not this one server process.
    state = _cap_state_path()
    if state is not None:
        if not state:
            return _tool_error(
                f"post_oracle_review: {CAP_STATE_ENV} is not set but this is "
                "an unattended run (GITHUB_RUN_ID is set) — the workflow must "
                "give every link step the same state-file path (the reeve.yml "
                "REEVE_GREENLIGHT_STATE pattern) or the one-review cap cannot "
                "span the chain walk; refusing to post")
        try:
            posted = _cap_state_count(state)
        except RuntimeError as e:
            return _tool_error(f"post_oracle_review: {e}")
        if posted >= MAX_POSTS_PER_RUN:
            return _tool_error(
                "the Oracle posts exactly ONE review per run and it is already "
                f"posted ({posted} recorded across the chain walk so far); "
                "refusing a second comment")
        try:
            _cap_state_ensure_appendable(state)
        except RuntimeError as e:
            return _tool_error(f"post_oracle_review: {e}")

    try:
        comment = _post_comment(body)
    except urllib.error.HTTPError as e:
        detail = e.read().decode(errors="replace")[:500] if hasattr(e, "read") else ""
        return _tool_error(f"GitHub API error {e.code} posting review: {detail}")
    except Exception as e:  # noqa: BLE001 — surface any failure to the agent
        return _tool_error(f"failed to post review: {type(e).__name__}: {e}")

    url = comment.get("html_url", "(unknown url)")
    if state:
        try:
            _cap_state_record(state, _pr_number(), url)
        except OSError as e:
            log(f"WARNING: posted {url} but could not append its "
                f"{CAP_STATE_ENV} record ({e}) — this post will not count "
                f"toward the walk cap")
    log(f"posted Oracle review: {url}")
    return _tool_text(f"POSTED {url}")


# --- MCP tool registry ------------------------------------------------------

TOOLS = [
    {
        "name": "post_oracle_review",
        "description": (
            "Post the ONE advisory Oracle review comment on the PR this run "
            "was launched for (the workflow fixes the PR number — it is not "
            "an argument). The body is passed as a JSON argument, so it may "
            "be full multi-line markdown with tables. The ORACLE_REVIEW "
            "marker, the advisory header and the Claude Code attribution "
            "footer are added automatically — write only the review itself. "
            "One post per run; a second call is refused."
        ),
        "inputSchema": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string",
                    "description": (
                        "The review body in markdown: verdict, contract-vs-"
                        "diff findings in both directions, what could not be "
                        "verified. Tables, pipes, backticks and newlines are "
                        "all fine here."
                    ),
                },
            },
            "required": ["body"],
            "additionalProperties": False,
        },
    }
]

_DISPATCH = {"post_oracle_review": _post_oracle_review}


def _tool_text(text):
    return {"content": [{"type": "text", "text": text}], "isError": False}


def _tool_error(text):
    log(text)
    return {"content": [{"type": "text", "text": f"Error: {text}"}], "isError": True}


# --- JSON-RPC over stdio (newline-delimited) --------------------------------

def _result(msg_id, result):
    return {"jsonrpc": "2.0", "id": msg_id, "result": result}


def _error(msg_id, code, message):
    return {"jsonrpc": "2.0", "id": msg_id, "error": {"code": code, "message": message}}


def handle(msg):
    """Map one JSON-RPC request to a response dict, or None for notifications."""
    method = msg.get("method")
    msg_id = msg.get("id")

    if msg_id is None and "id" not in msg:
        # Notifications get no response; ignore other id-less messages quietly.
        return None

    if method == "initialize":
        params = msg.get("params") or {}
        version = params.get("protocolVersion") or DEFAULT_PROTOCOL_VERSION
        return _result(
            msg_id,
            {
                "protocolVersion": version,
                "capabilities": {"tools": {}},
                "serverInfo": {"name": SERVER_NAME, "version": "1.0.0"},
            },
        )

    if method == "ping":
        return _result(msg_id, {})

    if method == "tools/list":
        return _result(msg_id, {"tools": TOOLS})

    if method == "tools/call":
        params = msg.get("params") or {}
        name = params.get("name")
        fn = _DISPATCH.get(name)
        if fn is None:
            return _result(msg_id, _tool_error(f"unknown tool: {name!r}"))
        return _result(msg_id, fn(params.get("arguments") or {}))

    return _error(msg_id, -32601, f"method not found: {method}")


def selftest():
    """Prove the write surface's security invariants fire, offline. A guard
    that is never exercised can be weakened and every other check stays green
    (the repo's standing rule), so these are the cases a live run cannot
    show."""
    global _last_payload
    os.environ["ORACLE_MCP_FAKE"] = "1"
    os.environ["GITHUB_REPOSITORY"] = "example/selftest"
    os.environ["ORACLE_PR"] = "123"
    fails = []

    def check(name, cond):
        print(f"{'ok  ' if cond else 'FAIL'}  {name}")
        if not cond:
            fails.append(name)

    def refused(r, needle):
        return r.get("isError") is True and needle in r["content"][0]["text"]

    # Pin the environment: each case below decides attended/unattended itself,
    # so an ambient Actions GITHUB_RUN_ID / ORACLE_CAP_STATE (this selftest
    # runs inside CI) must not leak into the attended cases.
    os.environ.pop("GITHUB_RUN_ID", None)
    os.environ.pop(CAP_STATE_ENV, None)

    # Input guards reject and post nothing.
    check("missing body is rejected",
          _post_oracle_review({}).get("isError") is True)
    check("oversized body is rejected",
          _post_oracle_review({"body": "x" * (MAX_BODY_BYTES + 1)}).get("isError") is True)

    # A valid post carries the hardcoded marker, header and footer, and goes to
    # the ORACLE_PR comment endpoint — no argument can change any of that.
    ok = _post_oracle_review({"body": "## Verdict\n| AC | held |\n|---|---|\nCONCUR"})
    check("a well-formed review posts", ok.get("isError") is False)
    check("the posted body carries the hardcoded marker",
          _last_payload["body"].startswith(MARKER))
    check("the posted body carries the advisory header",
          HEADER in _last_payload["body"])
    check("the posted body ends with the attribution footer",
          _last_payload["body"].endswith(FOOTER))
    check("the post targets the workflow-selected PR only",
          _last_path == "/repos/example/selftest/issues/123/comments")

    # Attended behavior: no GITHUB_RUN_ID means the cap is skipped — no state
    # file needed, and a human driving /oracle-review may post again.
    a1 = _post_oracle_review({"body": "attended one"})
    a2 = _post_oracle_review({"body": "attended two"})
    check("attended (no GITHUB_RUN_ID) skips the cap — no state file required",
          a1.get("isError") is False and a2.get("isError") is False)

    # A missing/invalid ORACLE_PR refuses rather than guessing a target.
    os.environ["ORACLE_PR"] = ""
    r = _post_oracle_review({"body": "x"})
    check("a missing ORACLE_PR is refused", r.get("isError") is True)
    os.environ["ORACLE_PR"] = "123"

    # The walk-spanning one-review cap, inside an Actions run.
    os.environ["GITHUB_RUN_ID"] = "selftest-run"

    # Unwired: run id set but no state path. Fail closed — per-process
    # counting is exactly the per-link reset the state file replaces.
    _last_payload = None
    r = _post_oracle_review({"body": "unwired"})
    check("an unattended run without ORACLE_CAP_STATE refuses (fail closed)",
          refused(r, f"{CAP_STATE_ENV} is not set") and _last_payload is None)

    with tempfile.TemporaryDirectory() as tmp:
        state = os.path.join(tmp, "oracle-posts")
        os.environ[CAP_STATE_ENV] = state

        # A post that FAILS does not consume the cap — the record is appended
        # only after a successful write.
        os.environ["ORACLE_PR"] = ""
        r = _post_oracle_review({"body": "will fail"})
        os.environ["ORACLE_PR"] = "123"
        check("a failed post does not consume the cap",
              r.get("isError") is True and _cap_state_count(state) == 0)

        # In-process: the first post goes through and is recorded; the second
        # is refused from the count the state file holds.
        r1 = _post_oracle_review({"body": "first"})
        check("the first post of a run goes through and appends one record",
              r1.get("isError") is False and _cap_state_count(state) == 1)
        try:
            with open(state, encoding="utf-8") as fh:
                recs = [json.loads(ln) for ln in fh if ln.strip()]
        except (OSError, ValueError):
            recs = []
        check("the state record names the workflow-selected PR",
              len(recs) == 1 and recs[0].get("pr") == 123)
        _last_payload = None
        r2 = _post_oracle_review({"body": "second"})
        check("a second post in the same run is refused",
              refused(r2, "ONE review") and _last_payload is None
              and _cap_state_count(state) == 1)

        # THE cross-process property: link N posts and then dies; link N+1 is
        # a FRESH process whose only memory of the run is the state file. A
        # real subprocess against the populated file is the exact situation the
        # old in-process counter got wrong.
        probe = [sys.executable, os.path.abspath(__file__), "--selftest-cap-child"]
        proc = subprocess.run(probe + [state], env=dict(os.environ),
                              capture_output=True, text=True)
        check("a fresh process counting from a state file at the cap refuses "
              "(the cross-process property)",
              proc.returncode == 0 and proc.stdout.startswith("REFUSED"))

        # Below the cap (link 1 died before posting) → the fresh process posts,
        # and the shared file advances — so the link after IT refuses too.
        state2 = os.path.join(tmp, "oracle-posts-2")
        proc = subprocess.run(probe + [state2], env=dict(os.environ),
                              capture_output=True, text=True)
        check("a fresh process below the cap posts (cross-process)",
              proc.returncode == 0 and proc.stdout.startswith("POSTED"))
        check("the fresh process's post advanced the shared state file",
              _cap_state_count(state2) == 1)
        proc = subprocess.run(probe + [state2], env=dict(os.environ),
                              capture_output=True, text=True)
        check("the next fresh process sees that post and refuses",
              proc.returncode == 0 and proc.stdout.startswith("REFUSED"))

        # An unreadable state path (a directory) refuses rather than counting
        # zero — a silent zero would silently uncap the walk.
        os.environ[CAP_STATE_ENV] = tmp
        _last_payload = None
        r = _post_oracle_review({"body": "unreadable"})
        check("an unreadable state file refuses (never counts as zero)",
              refused(r, "cannot read") and _last_payload is None)

        # A state path that cannot be appended (its directory is missing)
        # refuses BEFORE posting — a post it could not record would let a
        # later link post again.
        os.environ[CAP_STATE_ENV] = os.path.join(tmp, "missing-dir", "oracle-posts")
        _last_payload = None
        r = _post_oracle_review({"body": "unappendable"})
        check("an unappendable state path refuses before posting",
              refused(r, "cannot append") and _last_payload is None)

    os.environ.pop(CAP_STATE_ENV, None)
    os.environ.pop("GITHUB_RUN_ID", None)

    # The JSON-RPC surface only exposes the one tool.
    check("tools/list exposes exactly post_oracle_review",
          [t["name"] for t in TOOLS] == ["post_oracle_review"])

    if fails:
        print(f"\noracle_mcp selftest FAILED: {', '.join(fails)}")
        return 1
    print("\noracle_mcp selftest passed")
    return 0


def selftest_cap_child(state_path):
    """One posting attempt in THIS fresh process — the parent selftest's
    cross-process case. The parent's module state died with its process; the
    only thing this process knows about the run's posts is the state file it
    is handed, which is exactly link N+1's view after link N posted and died.
    Prints POSTED/REFUSED for the parent to assert on."""
    os.environ["ORACLE_MCP_FAKE"] = "1"
    os.environ["GITHUB_REPOSITORY"] = "example/selftest"
    os.environ["ORACLE_PR"] = "123"
    os.environ["GITHUB_RUN_ID"] = "selftest-link-n+1"
    os.environ[CAP_STATE_ENV] = state_path
    r = _post_oracle_review({"body": "cross-process probe"})
    outcome = "REFUSED" if r.get("isError") else "POSTED"
    print(f"{outcome}: {r['content'][0]['text']}")
    return 0


def main():
    if "--selftest" in sys.argv:
        raise SystemExit(selftest())
    if "--selftest-cap-child" in sys.argv:
        i = sys.argv.index("--selftest-cap-child")
        if i + 1 >= len(sys.argv):
            log("--selftest-cap-child needs the state-file path argument")
            raise SystemExit(2)
        raise SystemExit(selftest_cap_child(sys.argv[i + 1]))
    log(f"starting (repo={os.environ.get('GITHUB_REPOSITORY', '?')}, "
        f"pr={os.environ.get('ORACLE_PR', '?')}, "
        f"run={os.environ.get('GITHUB_RUN_ID', 'attended')})")
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            msg = json.loads(line)
        except json.JSONDecodeError as e:
            log(f"skipping unparseable line: {e}")
            continue
        try:
            response = handle(msg)
        except Exception as e:  # noqa: BLE001 — never let one message kill the loop
            log(f"handler error: {type(e).__name__}: {e}")
            response = _error(msg.get("id"), -32603, f"internal error: {e}")
        if response is not None:
            sys.stdout.write(json.dumps(response) + "\n")
            sys.stdout.flush()
    log("stdin closed, exiting")


if __name__ == "__main__":
    main()
