#!/usr/bin/env bash
# Coach-lock presence check (issue #806).
#
# claude-code-action exits 0 on a denial-only turn (#538 / #764 / #806), so
# a Design-coach job "success" does not mean a COACH-LOCK landed. This
# script is the pin: after a ship step that claimed success, the PR thread
# must carry a comment from the Actions bot whose body *ends* with the
# server-assembled suffix (`<!-- COACH_LOCK -->` immediately before the
# hardcoded Claude Code footer), created at or after this run's start.
# A substring planted by any other author, the human-visible
# `🎓 COACH-LOCK` line alone, a Jane/Drik/PM post that smuggled the
# marker bytes into its caller body (those jobs share
# `github-actions[bot]`), or a lock from an earlier coach run does not
# count.
#
# Live: ./scripts/coach-lock-check.sh <pr-number> --since <ISO8601>
# Offline: ./scripts/coach-lock-check.sh --selftest
set -euo pipefail

# A prior Bash-capable coach step can write PYTHONPATH/LD_PRELOAD via
# GITHUB_ENV. Isolated mode ignores those; also drop them in this shell
# so `gh` is not preloaded either.
unset PYTHONPATH PYTHONHOME PYTHONSTARTUP PYTHONUSERBASE \
      PYTHONEXECUTABLE LD_PRELOAD LD_LIBRARY_PATH LD_AUDIT \
      DYLD_INSERT_LIBRARIES BASH_ENV ENV || true
export PYTHONNOUSERSITE=1

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# Exact server-assembled marker (not the `<!-- COACH_LOCK` prefix, which
# would also match a forged `<!-- COACH_LOCK_FAKE -->`). Must sit immediately
# before the posting tool's hardcoded footer — a Jane/Drik/PM comment can
# carry the marker bytes in its caller body, and those jobs share
# github-actions[bot] with the coach.
MARKER_HTML='<!-- COACH_LOCK -->'
# Byte-identical to reviewer_mcp.py FOOTER.
COACH_FOOTER=$'---\n_Generated by [Claude Code](https://claude.ai/code)_'
export MARKER_HTML COACH_FOOTER

# Prefer the system interpreter; -I ignores PYTHONPATH/PYTHONHOME/user site.
if [[ -x /usr/bin/python3 ]]; then
  PYTHON3=/usr/bin/python3
else
  PYTHON3=python3
fi

comments_carry_lock() {
  "$PYTHON3" -I -c '
import json, os, sys

MARKER = os.environ["MARKER_HTML"]
FOOTER = os.environ["COACH_FOOTER"]
SUFFIX = MARKER + "\n\n" + FOOTER
BOT = "github-actions"
# When set (the workflow always sets it), only a comment created at or
# after this ISO8601 timestamp counts — a COACH-LOCK from an earlier
# coach run must not stamp a denial-only reopened/ready_for_review turn.
SINCE = (os.environ.get("COACH_LOCK_SINCE") or "").strip()


def is_actions_bot(comment):
    """REST login is github-actions[bot]; GraphQL is github-actions."""
    user = comment.get("user") or {}
    login = (user.get("login") or "").strip().lower()
    if login.endswith("[bot]"):
        login = login[:-5]
    return login == BOT


def flatten_pages(data):
    """gh api --paginate --slurp yields [page, page, ...]; one page alone
    without --slurp is a bare comment list. Accept both."""
    if not isinstance(data, list):
        return [data]
    if data and isinstance(data[0], list):
        return [c for page in data for c in page]
    return data


raw = sys.stdin.read().strip()
if not raw:
    raise SystemExit(1)
data = flatten_pages(json.loads(raw))
for c in data:
    body = c.get("body") or ""
    # post_coach assembles `{body}\n\n{MARKER}\n\n{FOOTER}`. A sibling
    # Actions-bot post (Jane/Drik/PM) always appends its own family
    # marker before the same footer, so a planted COACH_LOCK in the
    # caller body cannot be the suffix.
    if not (is_actions_bot(c) and body.endswith(SUFFIX)):
        continue
    if SINCE:
        created = (c.get("created_at") or "").strip()
        if not created or created < SINCE:
            continue
    raise SystemExit(0)
raise SystemExit(1)
'
}

selftest() {
  local n=0 bad=0
  local tmp
  tmp="$(mktemp -d)"
  trap 'rm -rf "$tmp"' RETURN

  expect() {
    local name="$1" json="$2" want="$3"
    n=$((n + 1))
    local rc=0
    comments_carry_lock <<<"$json" && rc=0 || rc=$?
    if [[ "$want" == pass && "$rc" -eq 0 ]]; then
      echo "ok    $name"
    elif [[ "$want" == fail && "$rc" -ne 0 ]]; then
      echo "ok    $name"
    else
      echo "FAIL  $name (want $want, exit $rc)"
      bad=1
    fi
  }

  local suffix='\n\n<!-- COACH_LOCK -->\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_'
  local bot='{"login":"github-actions[bot]","type":"Bot"}'

  unset COACH_LOCK_SINCE || true

  expect "Actions bot + the assembled marker-then-footer suffix passes" \
    '[{"body":"round 1'"${suffix}"'","user":'"${bot}"'}]' pass
  expect "GraphQL github-actions login + assembled suffix passes" \
    '[{"body":"kickoff'"${suffix}"'","user":{"login":"github-actions"}}]' pass
  expect "Actions bot + HTML marker and emoji kickoff with footer passes" \
    '[{"body":"🎓 COACH-LOCK\n\nkickoff'"${suffix}"'","user":'"${bot}"'}]' pass
  expect "a human comment carrying the HTML marker fails" \
    '[{"body":"kickoff'"${suffix}"'","user":{"login":"attacker"}}]' fail
  expect "cursor[bot] carrying the assembled suffix fails" \
    '[{"body":"kickoff'"${suffix}"'","user":{"login":"cursor[bot]","type":"Bot"}}]' fail
  expect "Actions bot + only the emoji kickoff fails" \
    '[{"body":"🎓 COACH-LOCK\n\nkickoff","user":'"${bot}"'}]' fail
  expect "a human emoji kickoff fails" \
    '[{"body":"🎓 COACH-LOCK\n\nkickoff","user":{"login":"attacker"}}]' fail
  expect "Actions bot + truncated HTML prefix fails" \
    '[{"body":"<!-- COACH_LOCK","user":'"${bot}"'}]' fail
  expect "Actions bot + marker bytes without the footer suffix fails" \
    '[{"body":"<!-- COACH_LOCK -->","user":'"${bot}"'}]' fail
  expect "Jane/Drik comments without a coach marker fail" \
    '[{"body":"<!-- JANE_SIGNOFF sha=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa verdict=pass fuse=none -->\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_","user":'"${bot}"'}]' fail
  expect "a Jane post that planted COACH_LOCK before its own sign-off fails" \
    '[{"body":"x\n\n<!-- COACH_LOCK -->\n\n<!-- JANE_SIGNOFF sha=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa verdict=pass fuse=none -->\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_","user":'"${bot}"'}]' fail
  expect "a Drik post that planted COACH_LOCK before its own sign-off fails" \
    '[{"body":"x\n\n<!-- COACH_LOCK -->\n\n<!-- DRIK_SIGNOFF sha=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa verdict=pass fuse=none -->\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_","user":'"${bot}"'}]' fail
  expect "a PM_TRIAGE post that planted COACH_LOCK before its own marker fails" \
    '[{"body":"x\n\n<!-- COACH_LOCK -->\n\n<!-- PM_TRIAGE design=demo sha=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa -->\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_","user":'"${bot}"'}]' fail
  expect "a Jane plant does not hide a later genuine coach lock" \
    '[{"body":"x\n\n<!-- COACH_LOCK -->\n\n<!-- JANE_SIGNOFF sha=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa verdict=pass fuse=none -->\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_","user":'"${bot}"'},{"body":"round 1'"${suffix}"'","user":'"${bot}"'}]' pass
  expect "an empty thread fails" '[]' fail
  expect "unrelated comments fail" \
    '[{"body":"lgtm","user":'"${bot}"'}]' fail
  expect "a marker with no author fails" \
    '[{"body":"kickoff'"${suffix}"'"}]' fail
  # --paginate --slurp wraps each page; flatten must still find the lock.
  expect "a slurped multi-page response still finds the lock" \
    '[[{"body":"page1","user":'"${bot}"'}],[{"body":"round 1'"${suffix}"'","user":'"${bot}"'}]]' pass

  # This-run scoping: an earlier lock must not stamp a denial-only re-run.
  export COACH_LOCK_SINCE="2026-10-04T12:00:00Z"
  expect "a lock created before --since fails" \
    '[{"body":"round 1'"${suffix}"'","created_at":"2026-10-04T11:59:59Z","user":'"${bot}"'}]' fail
  expect "a lock created at --since passes" \
    '[{"body":"round 1'"${suffix}"'","created_at":"2026-10-04T12:00:00Z","user":'"${bot}"'}]' pass
  expect "a lock created after --since passes" \
    '[{"body":"round 1'"${suffix}"'","created_at":"2026-10-04T12:00:01Z","user":'"${bot}"'}]' pass
  expect "an older plant does not hide a this-run coach lock" \
    '[{"body":"old'"${suffix}"'","created_at":"2026-10-04T11:00:00Z","user":'"${bot}"'},{"body":"new'"${suffix}"'","created_at":"2026-10-04T12:00:05Z","user":'"${bot}"'}]' pass
  expect "a this-run lock without created_at fails under --since" \
    '[{"body":"round 1'"${suffix}"'","user":'"${bot}"'}]' fail
  unset COACH_LOCK_SINCE

  echo "      selftest: $n cases"
  return "$bad"
}

if [[ "${1:-}" == "--selftest" ]]; then
  selftest
  echo "ok    coach-lock-check selftest passed"
  exit 0
fi

pr=""
since=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --since)
      if [[ $# -lt 2 || -z "${2:-}" ]]; then
        echo "usage: $0 <pr-number> --since <ISO8601> | --selftest" >&2
        exit 2
      fi
      since="$2"
      shift 2
      ;;
    -*)
      echo "usage: $0 <pr-number> --since <ISO8601> | --selftest" >&2
      exit 2
      ;;
    *)
      if [[ -n "$pr" ]]; then
        echo "usage: $0 <pr-number> --since <ISO8601> | --selftest" >&2
        exit 2
      fi
      pr="$1"
      shift
      ;;
  esac
done

if ! [[ "$pr" =~ ^[1-9][0-9]*$ ]]; then
  echo "usage: $0 <pr-number> --since <ISO8601> | --selftest" >&2
  exit 2
fi
if [[ -z "$since" ]]; then
  # Prefer the workflow env when the caller forgot the flag; still refuse
  # a live check with no bound — an earlier-run lock is not this round.
  since="${COACH_LOCK_SINCE:-}"
fi
if [[ -z "$since" ]]; then
  echo "FAIL  coach-lock-check: --since <ISO8601> (or COACH_LOCK_SINCE) is required so a lock from an earlier run cannot stamp this round" >&2
  exit 2
fi
# Loose ISO8601 shape (GitHub uses 2026-10-04T12:00:00Z).
if ! [[ "$since" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(Z|[+-][0-9]{2}:[0-9]{2})$ ]]; then
  echo "FAIL  coach-lock-check: --since must be an ISO8601 UTC timestamp (e.g. 2026-10-04T12:00:00Z); got ${since}" >&2
  exit 2
fi
export COACH_LOCK_SINCE="$since"

repo="${GITHUB_REPOSITORY:-}"
if [[ -z "$repo" ]]; then
  echo "FAIL  coach-lock-check: GITHUB_REPOSITORY is not set" >&2
  exit 2
fi

# --slurp wraps each page in an outer array so multi-page threads parse;
# without it, --paginate emits concatenated JSON arrays that json.loads
# cannot read, and a lock on a later page would be missed.
json="$(gh api --paginate --slurp \
  "repos/${repo}/issues/${pr}/comments?per_page=100")"
if comments_carry_lock <<<"$json"; then
  echo "ok    PR #${pr} carries a trusted COACH-LOCK from this run"
  exit 0
fi

echo "FAIL  PR #${pr} has no Actions-bot comment from this run ending with the assembled <!-- COACH_LOCK --> + footer suffix — a denial-only coach turn, a planted substring, a Jane/Drik/PM body smuggling the marker, or a lock from an earlier run is not a completed round (issue #806)" >&2
exit 1
