#!/usr/bin/env bash
# Coach-lock presence check (issue #806; completion marker issue #770).
#
# claude-code-action exits 0 on a denial-only turn (#538 / #764 / #806), so
# a Design-coach job "success" does not mean a COACH-LOCK landed. This
# script is the pin: after a ship step that claimed success, the PR thread
# must carry a comment from the Actions bot whose body *ends* with the
# server-assembled suffix
# (`<!-- COACH_LOCK -->` then `<!-- COACH_DONE sha=<40hex> -->` immediately
# before the hardcoded Claude Code footer), posted at or after this run's
# start (`--since`). A substring planted by any other author, the
# human-visible `🎓 COACH-LOCK` line alone, a Jane/Drik/PM post that
# smuggled the marker bytes into its caller body (those jobs share
# `github-actions[bot]`), or a COACH-LOCK left by an earlier coach run does
# not count.
#
# Live: ./scripts/coach-lock-check.sh <pr-number> --since <ISO8601>
# Offline: ./scripts/coach-lock-check.sh --selftest
set -euo pipefail

# A prior Bash-capable coach step can write PYTHONPATH/LD_PRELOAD via
# GITHUB_ENV. Isolated mode ignores those; also drop them in this shell
# so `gh` is not preloaded either.
unset PYTHONPATH PYTHONHOME PYTHONSTARTUP PYTHONUSERBASE \
      PYTHONEXECUTABLE LD_PRELOAD LD_LIBRARY_PATH LD_AUDIT \
      DYLD_INSERT_LIBRARIES BASH_ENV ENV || true
export PYTHONNOUSERSITE=1

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# Exact server-assembled markers (not the `<!-- COACH_LOCK` / `<!-- COACH_DONE`
# prefixes, which would also match forged `<!-- COACH_LOCK_FAKE -->`). The
# MCP posts COACH_LOCK then COACH_DONE (sha-bound, issue #770) then the
# footer — DONE is last so reviewer-posted.sh can endswith-match it; this
# check requires the full assembled pair.
MARKER_HTML='<!-- COACH_LOCK -->'
# Byte-identical to reviewer_mcp.py FOOTER.
COACH_FOOTER=$'---\n_Generated by [Claude Code](https://claude.ai/code)_'
export MARKER_HTML COACH_FOOTER

# Prefer the system interpreter; -I ignores PYTHONPATH/PYTHONHOME/user site.
if [[ -x /usr/bin/python3 ]]; then
  PYTHON3=/usr/bin/python3
else
  PYTHON3=python3
fi

comments_carry_lock() {
  "$PYTHON3" -I -c '
import json, os, re, sys

MARKER = os.environ["MARKER_HTML"]
FOOTER = os.environ["COACH_FOOTER"]
# post_coach assembles
#   {body}\n\n<!-- COACH_LOCK -->\n\n<!-- COACH_DONE sha=<40hex> -->\n\n{FOOTER}
# DONE is last (issue #770) so the artifact check can endswith-match it;
# requiring the full pair here keeps the lock pin unbroken.
SUFFIX_RE = re.compile(
    re.escape(MARKER) + r"\n\n<!-- COACH_DONE sha=[0-9a-f]{40} -->\n\n"
    + re.escape(FOOTER) + r"\Z"
)
BOT = "github-actions"
SINCE = os.environ.get("COACH_LOCK_SINCE", "").strip()


def is_actions_bot(comment):
    """REST login is github-actions[bot]; GraphQL is github-actions."""
    user = comment.get("user") or {}
    login = (user.get("login") or "").strip().lower()
    if login.endswith("[bot]"):
        login = login[:-5]
    return login == BOT


def load_comments(raw):
    """Decode `gh api --paginate` output into one comment list.

    One page is a JSON array. Multiple pages are either concatenated arrays
    (default --paginate) or an outer array of page arrays (--slurp). Either
    way every comment must be visible — a lock on page 2 must still count.
    """
    raw = raw.strip()
    if not raw:
        return []
    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        data = None
        decoder = json.JSONDecoder()
        idx = 0
        out = []
        while idx < len(raw):
            while idx < len(raw) and raw[idx].isspace():
                idx += 1
            if idx >= len(raw):
                break
            obj, end = decoder.raw_decode(raw, idx)
            if isinstance(obj, list):
                out.extend(obj)
            else:
                out.append(obj)
            idx = end
        return out
    if isinstance(data, list):
        if data and all(isinstance(p, list) for p in data):
            return [c for page in data for c in page]
        return data
    return [data]


raw = sys.stdin.read().strip()
if not raw:
    raise SystemExit(1)
for c in load_comments(raw):
    body = c.get("body") or ""
    # A sibling Actions-bot post (Jane/Drik/PM) always appends its own
    # family marker before the same footer, so a planted COACH_LOCK in
    # the caller body cannot be the suffix.
    if not (is_actions_bot(c) and SUFFIX_RE.search(body)):
        continue
    # A lock from an earlier coach run must not satisfy this round
    # (reopened / ready_for_review / denial-only turn).
    if SINCE:
        created = (c.get("created_at") or "").strip()
        if not created or created < SINCE:
            continue
    raise SystemExit(0)
raise SystemExit(1)
'
}

selftest() {
  local n=0 bad=0
  local tmp
  tmp="$(mktemp -d)"
  trap 'rm -rf "$tmp"' RETURN

  expect() {
    local name="$1" json="$2" want="$3"
    n=$((n + 1))
    local rc=0
    comments_carry_lock <<<"$json" && rc=0 || rc=$?
    if [[ "$want" == pass && "$rc" -eq 0 ]]; then
      echo "ok    $name"
    elif [[ "$want" == fail && "$rc" -ne 0 ]]; then
      echo "ok    $name"
    else
      echo "FAIL  $name (want $want, exit $rc)"
      bad=1
    fi
  }

  unset COACH_LOCK_SINCE || true

  expect "Actions bot + the assembled marker-then-footer suffix passes" \
    '[{"body":"round 1\n\n<!-- COACH_LOCK -->\n\n<!-- COACH_DONE sha=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa -->\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_","user":{"login":"github-actions[bot]","type":"Bot"}}]' pass
  expect "GraphQL github-actions login + assembled suffix passes" \
    '[{"body":"kickoff\n\n<!-- COACH_LOCK -->\n\n<!-- COACH_DONE sha=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa -->\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_","user":{"login":"github-actions"}}]' pass
  expect "Actions bot + HTML marker and emoji kickoff with footer passes" \
    '[{"body":"🎓 COACH-LOCK\n\nkickoff\n\n<!-- COACH_LOCK -->\n\n<!-- COACH_DONE sha=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa -->\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_","user":{"login":"github-actions[bot]"}}]' pass
  expect "a human comment carrying the HTML marker fails" \
    '[{"body":"kickoff\n\n<!-- COACH_LOCK -->\n\n<!-- COACH_DONE sha=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa -->\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_","user":{"login":"attacker"}}]' fail
  expect "cursor[bot] carrying the assembled suffix fails" \
    '[{"body":"kickoff\n\n<!-- COACH_LOCK -->\n\n<!-- COACH_DONE sha=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa -->\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_","user":{"login":"cursor[bot]","type":"Bot"}}]' fail
  expect "Actions bot + only the emoji kickoff fails" \
    '[{"body":"🎓 COACH-LOCK\n\nkickoff","user":{"login":"github-actions[bot]"}}]' fail
  expect "a human emoji kickoff fails" \
    '[{"body":"🎓 COACH-LOCK\n\nkickoff","user":{"login":"attacker"}}]' fail
  expect "Actions bot + truncated HTML prefix fails" \
    '[{"body":"<!-- COACH_LOCK","user":{"login":"github-actions[bot]"}}]' fail
  expect "Actions bot + marker bytes without the footer suffix fails" \
    '[{"body":"<!-- COACH_LOCK -->","user":{"login":"github-actions[bot]"}}]' fail
  expect "Actions bot + COACH_LOCK without COACH_DONE fails" \
    '[{"body":"round 1\n\n<!-- COACH_LOCK -->\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_","user":{"login":"github-actions[bot]"}}]' fail
  expect "Actions bot + COACH_DONE without COACH_LOCK fails" \
    '[{"body":"round 1\n\n<!-- COACH_DONE sha=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa -->\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_","user":{"login":"github-actions[bot]"}}]' fail
  expect "Jane/Drik comments without a coach marker fail" \
    '[{"body":"<!-- JANE_SIGNOFF sha=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa verdict=pass fuse=none -->\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_","user":{"login":"github-actions[bot]"}}]' fail
  expect "a Jane post that planted COACH_LOCK before its own sign-off fails" \
    '[{"body":"x\n\n<!-- COACH_LOCK -->\n\n<!-- JANE_SIGNOFF sha=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa verdict=pass fuse=none -->\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_","user":{"login":"github-actions[bot]"}}]' fail
  expect "a Drik post that planted COACH_LOCK before its own sign-off fails" \
    '[{"body":"x\n\n<!-- COACH_LOCK -->\n\n<!-- DRIK_SIGNOFF sha=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa verdict=pass fuse=none -->\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_","user":{"login":"github-actions[bot]"}}]' fail
  expect "a PM_TRIAGE post that planted COACH_LOCK before its own marker fails" \
    '[{"body":"x\n\n<!-- COACH_LOCK -->\n\n<!-- PM_TRIAGE design=demo sha=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa -->\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_","user":{"login":"github-actions[bot]"}}]' fail
  expect "a Jane plant does not hide a later genuine coach lock" \
    '[{"body":"x\n\n<!-- COACH_LOCK -->\n\n<!-- JANE_SIGNOFF sha=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa verdict=pass fuse=none -->\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_","user":{"login":"github-actions[bot]"}},{"body":"round 1\n\n<!-- COACH_LOCK -->\n\n<!-- COACH_DONE sha=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa -->\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_","user":{"login":"github-actions[bot]"}}]' pass
  expect "an empty thread fails" '[]' fail
  expect "unrelated comments fail" \
    '[{"body":"lgtm","user":{"login":"github-actions[bot]"}}]' fail
  expect "a marker with no author fails" \
    '[{"body":"kickoff\n\n<!-- COACH_LOCK -->\n\n<!-- COACH_DONE sha=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa -->\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"}]' fail
  expect "concatenated paginated page arrays still find the lock" \
    '[{"body":"page1","user":{"login":"github-actions[bot]"}}][{"body":"round 1\n\n<!-- COACH_LOCK -->\n\n<!-- COACH_DONE sha=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa -->\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_","user":{"login":"github-actions[bot]"}}]' pass
  expect "slurped page arrays still find the lock" \
    '[[{"body":"page1","user":{"login":"github-actions[bot]"}}],[{"body":"round 1\n\n<!-- COACH_LOCK -->\n\n<!-- COACH_DONE sha=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa -->\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_","user":{"login":"github-actions[bot]"}}]]' pass

  export COACH_LOCK_SINCE=2026-10-04T12:00:00Z
  expect "a lock created after --since passes" \
    '[{"body":"round 1\n\n<!-- COACH_LOCK -->\n\n<!-- COACH_DONE sha=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa -->\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_","created_at":"2026-10-04T12:00:01Z","user":{"login":"github-actions[bot]"}}]' pass
  expect "a lock created at exactly --since passes" \
    '[{"body":"round 1\n\n<!-- COACH_LOCK -->\n\n<!-- COACH_DONE sha=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa -->\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_","created_at":"2026-10-04T12:00:00Z","user":{"login":"github-actions[bot]"}}]' pass
  expect "a lock from an earlier run fails under --since" \
    '[{"body":"round 1\n\n<!-- COACH_LOCK -->\n\n<!-- COACH_DONE sha=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa -->\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_","created_at":"2026-10-04T11:59:59Z","user":{"login":"github-actions[bot]"}}]' fail
  expect "a lock missing created_at fails under --since" \
    '[{"body":"round 1\n\n<!-- COACH_LOCK -->\n\n<!-- COACH_DONE sha=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa -->\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_","user":{"login":"github-actions[bot]"}}]' fail
  expect "an earlier lock does not hide a later in-window lock" \
    '[{"body":"old\n\n<!-- COACH_LOCK -->\n\n<!-- COACH_DONE sha=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa -->\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_","created_at":"2026-10-04T11:00:00Z","user":{"login":"github-actions[bot]"}},{"body":"new\n\n<!-- COACH_LOCK -->\n\n<!-- COACH_DONE sha=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa -->\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_","created_at":"2026-10-04T12:30:00Z","user":{"login":"github-actions[bot]"}}]' pass
  unset COACH_LOCK_SINCE || true

  echo "      selftest: $n cases"
  return "$bad"
}

if [[ "${1:-}" == "--selftest" ]]; then
  selftest
  echo "ok    coach-lock-check selftest passed"
  exit 0
fi

pr=""
since=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --since)
      if [[ $# -lt 2 || -z "${2:-}" ]]; then
        echo "usage: $0 <pr-number> --since <ISO8601> | --selftest" >&2
        exit 2
      fi
      since="$2"
      shift 2
      ;;
    --since=*)
      since="${1#--since=}"
      if [[ -z "$since" ]]; then
        echo "usage: $0 <pr-number> --since <ISO8601> | --selftest" >&2
        exit 2
      fi
      shift
      ;;
    -*)
      echo "usage: $0 <pr-number> --since <ISO8601> | --selftest" >&2
      exit 2
      ;;
    *)
      if [[ -n "$pr" ]]; then
        echo "usage: $0 <pr-number> --since <ISO8601> | --selftest" >&2
        exit 2
      fi
      pr="$1"
      shift
      ;;
  esac
done

if ! [[ "$pr" =~ ^[1-9][0-9]*$ ]]; then
  echo "usage: $0 <pr-number> --since <ISO8601> | --selftest" >&2
  exit 2
fi

if [[ -z "$since" ]]; then
  since="${COACH_LOCK_SINCE:-}"
fi
if [[ -z "$since" ]]; then
  echo "FAIL  coach-lock-check: --since <ISO8601> (or COACH_LOCK_SINCE) is required so a lock from an earlier run cannot stamp this round" >&2
  exit 2
fi
# ISO-8601 UTC to the second (YYYY-MM-DDTHH:MM:SSZ) — lexical compare
# matches chronological order for this fixed-width form.
if ! [[ "$since" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$ ]]; then
  echo "FAIL  coach-lock-check: --since must be UTC ISO8601 to the second (YYYY-MM-DDTHH:MM:SSZ); got ${since}" >&2
  exit 2
fi
export COACH_LOCK_SINCE="$since"

repo="${GITHUB_REPOSITORY:-}"
if [[ -z "$repo" ]]; then
  echo "FAIL  coach-lock-check: GITHUB_REPOSITORY is not set" >&2
  exit 2
fi

# --paginate --slurp wraps each page in an outer array so multi-page
# threads parse as one JSON document. load_comments() also accepts the
# concatenated (no --slurp) shape as a belt-and-braces.
json="$(gh api --paginate --slurp "repos/${repo}/issues/${pr}/comments?per_page=100")"
if comments_carry_lock <<<"$json"; then
  if [[ -n "${COACH_LOCK_SINCE:-}" ]]; then
    echo "ok    PR #${pr} carries a trusted COACH-LOCK from this run (since ${COACH_LOCK_SINCE})"
  else
    echo "ok    PR #${pr} carries a trusted COACH-LOCK"
  fi
  exit 0
fi

echo "FAIL  PR #${pr} has no Actions-bot comment ending with the assembled <!-- COACH_LOCK --> + <!-- COACH_DONE sha=… --> + footer suffix for this run — a denial-only coach turn, a planted substring, a Jane/Drik/PM body smuggling the marker, or a lock from an earlier run is not a completed round (issue #806)" >&2
exit 1
