#!/usr/bin/env bash
# Docs-drift check: assert the docs match the tree, so staleness fails fast.
# Run by check.sh (and therefore by /preflight and CI's scad-check jobs).
#
# Scope discipline (deliberate, keep it this way): every check here is a
# MECHANICAL fact — a file exists, a name is mentioned — verified with
# test/grep against the filesystem. The moment a check tries to verify a
# prose claim ("gate.sh --slice is what CI enforces") it becomes flaky and
# earns deletion. Judgment calls about prose belong to reviewer skills,
# not bash.
set -euo pipefail

cd "$(dirname "$0")/.."

fail=0
err() { echo "FAIL  docs: $1"; fail=1; }

# Gallery-freshness placement. The gallery is regenerated by CI's regen job,
# so in CI this one check is split out of the pack: the scad-check jobs run
# with DOCS_CHECK_GALLERY=skip so they need not wait for regen (that wait
# roughly doubled CI wall time — every other check here reads sources regen
# never touches), and the design-docs job, which does wait on regen, runs
# `--gallery-only` to assert freshness against the post-regen tree. Locally
# neither is set and everything runs, unchanged.
GALLERY_MODE="${DOCS_CHECK_GALLERY:-check}"
[[ "${1:-}" == "--gallery-only" ]] && GALLERY_MODE=only

gallery_check() {
  ./scripts/gallery.sh --check >/dev/null \
    || err "README gallery is stale — run ./scripts/gallery.sh"
}

if [[ "$GALLERY_MODE" == only ]]; then
  gallery_check
  (( fail )) || echo "ok    README gallery is current"
  exit "$fail"
fi

# 1. Every top-level directory appears in CLAUDE.md's and README.md's
#    layout docs (generated/infra dirs allowlisted). tools/ is expanded one
#    level: each tool is its own component with its own docs, and checking
#    only the `tools/` parent let tools/photoshot/ land undocumented in both
#    files while the check stayed green.
ALLOW=" build .git .claude .github "
dirs=()
for dir in */ .*/; do
  d="${dir%/}"
  [[ "$d" == "." || "$d" == ".." ]] && continue
  [[ "$ALLOW" == *" $d "* ]] && continue
  dirs+=("$d")
done
for dir in tools/*/; do
  [[ -d "$dir" ]] && dirs+=("${dir%/}")
done
for d in "${dirs[@]}"; do
  grep -qF "${d}/" CLAUDE.md || err "${d}/ not mentioned in CLAUDE.md"
  grep -qF "${d}/" README.md || err "${d}/ not mentioned in README.md"
done

# 2. Skills <-> CLAUDE.md, both directions. Boundary-aware match so a
#    longer name (e.g. /resume-design) can't satisfy a shorter one.
for skill in .claude/skills/*/; do
  s="$(basename "$skill")"
  grep -qE "/${s}([^a-z0-9-]|\$)" CLAUDE.md \
    || err "skill .claude/skills/${s} not mentioned in CLAUDE.md"
done
while read -r ref; do
  [[ -d ".claude/skills/${ref}" ]] \
    || err "CLAUDE.md names skill /${ref} but .claude/skills/${ref} does not exist"
done < <(grep -oE '`/[a-z0-9-]+' CLAUDE.md | sed 's|^`/||' | sort -u)

# 3. Every design ships the NOTES.md the co-design workflow requires
#    (README.md is readme-gate.sh's job).
for dir in designs/*/; do
  n="$(basename "$dir")"
  [[ -f "designs/${n}/${n}.scad" ]] || continue
  [[ -f "designs/${n}/NOTES.md" ]] || err "designs/${n}/ has no NOTES.md"
done

# 3b. Every style ships a complete pack, and appears in the styles catalog.
#     (The pack's internal consistency — style.scad and STYLE.md matching
#     style.json — is scripts/style-check.sh's job; this is the file census.)
for dir in styles/*/; do
  n="$(basename "$dir")"
  [[ -f "styles/${n}/style.json" ]] || continue
  for f in STYLE.md style.scad swatch.scad previews/swatch.png; do
    [[ -f "styles/${n}/${f}" ]] || err "styles/${n}/ has no ${f}"
  done
  grep -q "${n}/STYLE.md" styles/README.md \
    || err "style ${n} is not listed in styles/README.md"
done

# 4. The README gallery has one fresh row per design, no orphans.
#    (Skipped under DOCS_CHECK_GALLERY=skip — see the note at the top.)
if [[ "$GALLERY_MODE" != skip ]]; then
  gallery_check
fi

# 5. Freshness canary where docs quote reality: every file in scripts/ is
#    named in both CLAUDE.md and README.md. Boundary-aware match so e.g.
#    readme-gate.sh can't satisfy the check for gate.sh.
#
#    For CLAUDE.md the match is scoped to the `scripts/` layout bullet, not
#    the whole file. Matching anywhere is what let product-shot.sh land: it
#    was named in the Commands block, so the check passed while the layout
#    bullet — the one place claiming to enumerate the toolchain — silently
#    fell out of date. The bullet is one line starting "- `scripts/`".
# `--` before the pattern: it starts with "-", which grep would otherwise
# parse as an option bundle and reject.
scripts_bullet="$(grep -m1 -F -- '- `scripts/`' CLAUDE.md || true)"
[[ -n "$scripts_bullet" ]] \
  || err "CLAUDE.md has no '- \`scripts/\`' layout bullet to check against"
for f in scripts/*; do
  # regular files only: `scripts/*` also globs generated directories such as
  # __pycache__ (gitignored, but present after anything imports gate-summary),
  # and demanding those be documented is nonsense.
  [[ -f "$f" ]] || continue
  b="$(basename "$f")"
  b_re="${b//./\\.}"
  pat="(^|[^a-zA-Z0-9._-])${b_re}([^a-zA-Z0-9_-]|\$)"
  grep -qE "$pat" <<<"$scripts_bullet" \
    || err "scripts/${b} missing from CLAUDE.md's \`scripts/\` layout bullet"
  grep -qE "$pat" README.md || err "scripts/${b} not mentioned in README.md"
done

# 6. Same canary for lib/: every first-party library is named in CLAUDE.md and
#    README.md, and ships the demo CLAUDE.md requires. Written as a check
#    rather than trusted to review because that rule had no enforcement at all
#    — threads-fdm.scad landed while README's lib/ bullet still said the only
#    shared module was printability.scad. lib/*.scad is the top level only, so
#    vendored lib/BOSL2/ is excluded by the glob; *-demo.scad files are the
#    artifacts of the rule, not subjects of it.
#
#    README's match is scoped to its `## Layout` section and demands the
#    backticked filename, for the same reason the scripts/ check is scoped to
#    one bullet: a passing mention anywhere else in the file would let the
#    layout list — the one place claiming to enumerate the libraries — go stale
#    while the check stayed green.
readme_layout="$(awk '/^## Layout/{f=1;next} /^## /{f=0} f' README.md)"
[[ -n "$readme_layout" ]] || err "README.md has no '## Layout' section to check against"
for f in lib/*.scad; do
  b="$(basename "$f" .scad)"
  [[ "$b" == *-demo ]] && continue
  grep -qF "lib/${b}.scad" CLAUDE.md || err "lib/${b}.scad not named in CLAUDE.md"
  grep -qF "\`${b}.scad\`" <<<"$readme_layout" \
    || err "lib/${b}.scad not named in README.md's \`## Layout\` section"
  [[ -f "lib/${b}-demo.scad" ]] \
    || err "lib/${b}.scad has no lib/${b}-demo.scad (CLAUDE.md requires one per first-party library)"
done

# 7. Shebang <=> executable, on the COMMITTED mode. Every file in scripts/
#    that opens with a #! line is a command and must be 100755 in the index;
#    a file without one (today only preview-budget.sh, a sourced helper) is
#    correctly 100644. The committed mode is what regressed on site.sh
#    (issue #61): nothing in CI invokes most scripts by ./path, so a 644
#    commit ships silently and only a human following the docs hits
#    "Permission denied". `git ls-files -s` reads the index, not the
#    filesystem — a local chmod can't mask what a fresh clone will get.
while read -r mode _ _ path; do
  [[ -f "$path" ]] || continue
  first="$(head -c 2 "$path")"
  if [[ "$first" == '#!' && "$mode" != 100755 ]]; then
    err "${path} has a shebang but is committed mode ${mode} — 'git update-index --chmod=+x ${path}' (issue #61)"
  elif [[ "$first" != '#!' && "$mode" == 100755 ]]; then
    err "${path} is committed executable but has no shebang — sourced helpers stay 100644"
  fi
done < <(git ls-files -s scripts/)

# 8. Every OpenSCAD invocation in scripts/ goes through $OPENSCAD_BIN. The
#    contract is documented in CLAUDE.md and CI's render path sets
#    OPENSCAD_BIN=openscad-nightly, so a script that hardcodes the binary
#    works everywhere EXCEPT the one CI job that installs only the nightly —
#    animate.sh shipped exactly that and failed as "openscad: not found" in
#    regen alone (issue #85, bug 1). Two invocation shapes are flagged: a
#    literal `openscad` handed to xvfb-run, and one in direct command
#    position. Comment lines pass (prose may quote the bad shape when
#    documenting it); nothing else does — compliant invocations never
#    contain the lowercase literal, and the default assignment
#    (OPENSCAD_BIN="${OPENSCAD_BIN:-openscad}") sits outside both
#    invocation shapes, so no allowance for lines mentioning OPENSCAD_BIN
#    is needed and none is made (a violation sharing a line with the
#    variable still fails — Copilot review on #90).
for f in scripts/*.sh; do
  while IFS=: read -r ln line; do
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    err "${f}:${ln} invokes a literal openscad binary — route it through \"\$OPENSCAD_BIN\" (issue #85)"
  done < <(grep -nE '(xvfb-run[^|#]*[[:space:]]|^[[:space:]]*|[|;&][[:space:]]*|\$\([[:space:]]*)openscad(-nightly)?([[:space:]]|$)' "$f" || true)
done

# 9. Cached apt packages must be postinst-free. awalsh128/cache-apt-pkgs-action
#    restores a package's FILE LIST without replaying its postinst, so a
#    package that builds update-alternatives symlinks in postinst (ImageMagick:
#    /usr/bin/montage -> /etc/alternatives/montage) comes back with those
#    names dangling — and it fails one run LATE: the cold run installs
#    normally and passes, the restore breaks whoever pushes next (issue #85,
#    bug 2). The allowlist below is the set verified postinst-free (dpkg -I:
#    control tarball carries no postinst, no alternatives registration).
#    Adding a package to a cached `packages:` list means verifying it the
#    same way and extending this list in the same PR — or installing it with
#    plain apt-get as the regen job and lifestyle-shot.yml deliberately do.
while IFS=: read -r wf pkgs; do
  for p in $pkgs; do
    case "$p" in
      xvfb|openscad|openscad-mcad|prusa-slicer|f3d) ;;
      *) err "${wf} caches apt package '${p}' which is not on the verified postinst-free allowlist — cache-apt restores skip postinst, so alternatives-managed binaries come back dangling one run later (issue #85); verify with dpkg -I and extend the allowlist here, or use plain apt-get" ;;
    esac
  done
done < <(awk '/awalsh128\/cache-apt-pkgs-action/{f=1}
              f && /^[[:space:]]*packages:/{
                sub(/^[[:space:]]*packages:[[:space:]]*/,"");
                print FILENAME ":" $0; f=0
              }' .github/workflows/*.yml)

# 10. The contributor guide must not regress to the pre-#544 vendor claim.
#     The four chain-walking routines walk GLM links then an Anthropic tail,
#     so "never cross vendors" is false; a mechanical literal check (the
#     phrase is absent), not a judgment about the prose that replaced it.
grep -qiF "never cross vendors" docs/contributing/autonomy.md \
  && err "docs/contributing/autonomy.md still says chains 'never cross vendors' — the routines walk a cross-provider tail since #544; describe the head-provider + layout rule instead"

if [[ "$fail" == 0 ]]; then
  echo "ok    docs match the tree"
fi
exit "$fail"
