#!/usr/bin/env bash
# Regenerate the design gallery section of the top-level README.md.
#   ./scripts/gallery.sh          # rewrite README.md between the markers
#   ./scripts/gallery.sh --check  # exit 1 if the committed gallery is stale
#
# One row per design directory: contact-sheet thumbnail (from
# designs/<name>/previews/contact-sheet.png, rendered fresh if missing),
# a one-liner scraped from NOTES.md's "## Goal" section (falling back to
# the README product page's intro pitch), and a link to the design dir.
# Only the region between the markers is touched — hand-written prose
# around it survives regeneration. Run after adding or renaming a design;
# check.sh fails if the committed gallery drifts from the design list.
#
# Row order and nesting come from `./scripts/lineage.sh order`, not from the
# designs/*/ glob: a derivative listed as a peer of the design whose geometry
# it reuses reads as an independent design, and the reader has no way to tell
# otherwise. Derivative rows (depth > 0) get a ↳ lead-in and name their
# parents in the text column.
set -euo pipefail

cd "$(dirname "$0")/.."

BEGIN='<!-- gallery:begin (generated by scripts/gallery.sh — edit prose outside the markers) -->'
END='<!-- gallery:end -->'

CHECK=0
[[ "${1:-}" == "--check" ]] && CHECK=1

# one-liner for a design: NOTES.md "## Goal" paragraph, else README intro
pitch() {
  local name="$1" line
  line="$(awk '/^##[[:space:]]+Goal/ { hit=1; next }
               hit && /^[[:space:]]*$/ { if (got) exit; next }
               hit && /^#/ { exit }
               hit { printf "%s ", $0; got=1 }' \
          "designs/${name}/NOTES.md" 2>/dev/null || true)"
  if [[ -z "$line" ]]; then
    line="$(awk 'NR==1 && /^#/ { next }
                 /^[[:space:]]*$/ { next }
                 /^[#!\[|<]/ { next }
                 { print; exit }' "designs/${name}/README.md" 2>/dev/null || true)"
  fi
  line="$(echo "$line" | sed 's/[[:space:]]*$//')"
  # a Goal paragraph that leads into a list ends with "...:" — drop the
  # dangling fragment and keep the complete sentences before it
  if [[ "$line" == *: && "$line" == *.* ]]; then
    line="${line%.*}."
  fi
  # escape table delimiters so a pitch containing | can't add columns
  printf '%s' "$line" | sed 's/|/\\|/g'
}

# The lineage sentence printed under a derivative's pitch. Every parent is
# named, not just the one the row nests under: two parents defining the same
# module are resolved by last-include-wins, silently, so a reader shown only
# the first parent would be reading the wrong credit for whatever the last one
# supplied. Parents arrive in include order — that is the order that decides.
lineage_line() {
  local name="$1" out parents=() links=() p
  if ! out="$(./scripts/lineage.sh parents "$name")"; then
    echo "gallery: ./scripts/lineage.sh parents ${name} failed" >&2
    exit 1
  fi
  mapfile -t parents < <(printf '%s' "$out")
  if (( ${#parents[@]} == 0 )); then
    # Unreachable via `order`, which only nests a design under a parent it
    # actually has. If it ever happens the two commands disagree, and a
    # lineage row with no lineage is worse than no gallery.
    echo "gallery: ${name} is nested as a derivative but reports no parents" >&2
    exit 1
  fi
  for p in "${parents[@]}"; do
    links+=("[${p}](designs/${p}/)")
  done
  if (( ${#links[@]} == 1 )); then
    printf '_derived from %s_' "${links[0]}"
  else
    local rest
    rest="$(printf ', then %s' "${links[@]:1}")"
    printf '_derived from %s%s — last include wins_' "${links[0]}" "$rest"
  fi
}

gallery() {
  echo "$BEGIN"
  # Order AND grouping come from scripts/catalog.sh (issue #374): the one
  # authoritative grouped, lineage-ordered sequence both this gallery and the
  # site index consume, so the two surfaces can't disagree about a design's
  # group. Each line is
  #   <group-slug> \t <group-label> \t <depth> \t <name> \t <parent>
  # with groups in the display order of designs/categories.conf and, within a
  # group, lineage order (a derivative still nests under its parent, and both
  # sit in the same group). No fallback to a flat glob when it fails: a gallery
  # that quietly drops its nesting or grouping is the same silent-wrong-output
  # failure the derivative machinery exists to catch — the page still renders,
  # still looks finished, and is wrong about which design is whose.
  local order
  if ! order="$(./scripts/catalog.sh order)"; then
    echo "gallery: ./scripts/catalog.sh order failed — refusing to emit a gallery with the grouping missing" >&2
    exit 1
  fi

  # Census cross-check. `catalog order` (field 4 is the name) and the glob below
  # are both meant to mean "a directory under designs/ with a .scad matching its
  # name"; if they ever stop meaning the same thing, the symptom is a design
  # silently absent from the gallery, with docs-check.sh's staleness check none
  # the wiser because the generated file still matches the committed one.
  local from_order from_glob dir
  from_order="$(awk -F'\t' 'NF { print $4 }' <<<"$order" | sort)"
  from_glob="$(for dir in designs/*/; do
      dir="$(basename "$dir")"
      [[ -f "designs/${dir}/${dir}.scad" ]] || continue
      echo "$dir"
    done | sort)"
  if [[ "$from_order" != "$from_glob" ]]; then
    echo "gallery: catalog order and designs/*/ disagree about which designs exist:" >&2
    diff <(printf '%s\n' "$from_glob") <(printf '%s\n' "$from_order") >&2 || true
    exit 1
  fi

  # Per-group promise blurbs, from the same authority (catalog.sh) as the order,
  # so a heading and its promise can't drift from the vocabulary. Each line is
  # <slug> \t <label> \t <blurb> (blurb empty for the navigational headings).
  local groups_out
  if ! groups_out="$(./scripts/catalog.sh groups)"; then
    echo "gallery: ./scripts/catalog.sh groups failed" >&2
    exit 1
  fi
  local -A group_blurb=()
  local gslug gblurb
  while IFS=$'\t' read -r gslug _ gblurb; do
    [[ -n "$gslug" ]] || continue
    group_blurb["$gslug"]="$gblurb"
  done <<<"$groups_out"

  # A `### <group>` heading opens each group, followed by a fresh table header:
  # markdown breaks a table at a heading, so a genuine subheading forces one
  # table per group. The parent field (5th) is dropped on purpose: lineage_line
  # re-asks for the whole include-ordered parent list, of which the primary
  # parent is only the first entry, and a row that named one parent while the
  # design declared two would be exactly the half-truth this nesting is for.
  local cur_group="" group label depth name
  while IFS=$'\t' read -r group label depth name _; do
    [[ -n "$name" ]] || continue
    if [[ "$group" != "$cur_group" ]]; then
      printf '\n### %s\n\n' "$label"
      if [[ -n "${group_blurb[$group]:-}" ]]; then
        printf '_%s_\n\n' "${group_blurb[$group]}"
      fi
      echo "| Design | |"
      echo "|---|---|"
      cur_group="$group"
    fi
    local thumb="designs/${name}/previews/contact-sheet.png"
    if [[ ! -f "$thumb" ]]; then
      if [[ "$CHECK" == 1 ]]; then
        echo "gallery --check: ${thumb} missing — run ./scripts/gallery.sh" >&2
        exit 1
      fi
      echo "gallery: rendering missing ${thumb}" >&2
      ./scripts/render.sh "$name" >&2
      mkdir -p "designs/${name}/previews"
      cp "build/${name}.png" "$thumb"
    fi
    if (( depth == 0 )); then
      printf '| <a href="designs/%s/"><img src="%s" width="320" alt="%s previews"></a> | **[%s](designs/%s/)** — %s |\n' \
        "$name" "$thumb" "$name" "$name" "$name" "$(pitch "$name")"
    else
      # A derivative of a derivative steps in one more level. &nbsp; rather
      # than spaces because markdown collapses leading whitespace in a cell,
      # which would flatten the very nesting this row exists to show.
      local indent="" i
      for (( i = 1; i < depth; i++ )); do
        indent+="&nbsp;&nbsp;"
      done
      # Assigned before the printf and status-tested explicitly. Two reasons,
      # both measured: a command substitution that dies inside printf's own
      # argument list still leaves printf exiting 0, and errexit does not reach
      # in here at all — this whole function runs inside `$(gallery)`, and a
      # failing command inside a command substitution does not abort it. Bare
      # `lineage="$(lineage_line ...)"` printed a row with the lineage blank
      # and the script went on to rewrite README.md and report success. Every
      # failure below the top level has to be an explicit exit.
      local lineage
      if ! lineage="$(lineage_line "$name")"; then
        exit 1
      fi
      printf '| <a href="designs/%s/"><img src="%s" width="320" alt="%s previews"></a> | %s↳ **[%s](designs/%s/)** — %s<br>%s |\n' \
        "$name" "$thumb" "$name" "$indent" "$name" "$name" "$(pitch "$name")" "$lineage"
    fi
  done <<<"$order"
  echo "$END"
}

if ! grep -qF "$BEGIN" README.md || ! grep -qF "$END" README.md; then
  echo "error: README.md is missing the gallery markers" >&2
  exit 1
fi

new="$(gallery)"
# splice: everything before BEGIN, the fresh gallery, everything after END
out="$(awk -v begin="$BEGIN" -v end="$END" -v repl="$new" '
  index($0, begin) { print repl; skip=1; next }
  index($0, end)   { skip=0; next }
  !skip { print }' README.md)"

if [[ "$CHECK" == 1 ]]; then
  if [[ "$out" != "$(cat README.md)" ]]; then
    echo "gallery --check: README.md gallery is stale — run ./scripts/gallery.sh" >&2
    exit 1
  fi
  echo "gallery: up to date"
else
  printf '%s\n' "$out" > README.md
  echo "gallery: README.md updated"
fi
