#!/usr/bin/env bash
# gh-project.sh — emit a repeatable `gh` recipe that provisions the
# "print-bench autonomy" GitHub Projects (v2) board (issue #148).
#
# WHY a recipe you run, not an API call the automation makes: this session's
# tooling cannot create or populate a Projects v2 board (the board/field/item
# API is GraphQL-only and unavailable here), and a Project is settings-shaped
# anyway. So the board's schema lives HERE as the committed source of truth, and
# `setup` prints the exact, idempotent `gh` commands that create it — reviewable
# before you run it, and repeatable in the future. Populating the board (adding
# issues, setting fields) is the follow-up automation slice; see
# docs/roadmap-board.md.
#
# Usage:
#   scripts/gh-project.sh setup         # print the idempotent board-provisioning recipe
#   scripts/gh-project.sh setup | bash  # run it (needs gh >= 2.30 + jq + the `project` scope)
#   scripts/gh-project.sh add-item <issue-or-pr-url> [--stage <name>] [--points <n>]
#                                       # print an idempotent recipe that adds ONE issue/PR to the
#                                       # board and sets its Stage / Story points; pipe to bash to run
#   scripts/gh-project.sh --selftest    # prove the emitted recipes are valid, well-formed bash (run by check.sh)
#
# AUTH: `gh project` requires the `project` token scope, which login does NOT
# grant by default and which a `contents:write` fine-grained PAT (e.g.
# REGEN_TOKEN) does NOT include; the Actions GITHUB_TOKEN cannot touch Projects
# v2 at all. The recipe runs `gh auth refresh -s project` first. For the
# automation slice, add the Projects (read/write) permission to the token — see
# docs/roadmap-board.md.
set -euo pipefail

SELF="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd)/$(basename "$0")"

die() { echo "gh-project: $*" >&2; exit 1; }

# ---- the board spec: the committed source of truth -------------------------
# Change these to reshape the board; the emitted recipe is idempotent, so
# re-running it reconciles the live board to this spec.
PROJECT_TITLE="print-bench autonomy"
PROJECT_OWNER="shaiss"
# Our pipeline stage, as a distinct SINGLE_SELECT field. GitHub gives every
# board a built-in "Status" (Todo/In Progress/Done) the CLI cannot reshape, so
# we add "Stage" instead and group the board by it in the UI (view config is
# UI-only). Options are ordered; names only (the CLI can't set colours).
STAGE_FIELD="Stage"
STAGE_OPTIONS="Backlog,Ready,In progress,In review,Done"
# Story points, a NUMBER field. Fibonacci 1/2/3/5/8 by convention: a chunked,
# one-PR sub-issue is 1-3; a bigger estimate is a hint it should be re-chunked.
POINTS_FIELD="Story points"

# Emit the provisioning recipe from the spec above. Deterministic and
# side-effect-free: it only prints. The spec values are substituted into a
# header (unquoted heredoc); the body is literal (quoted heredoc) and reads them
# as its own runtime variables, so the recipe is the single source and this
# emitter needs no `gh` itself.
emit_recipe() {
  cat <<EOF
#!/usr/bin/env bash
# Provision the "$PROJECT_TITLE" GitHub Project (v2). Idempotent — re-run to
# reconcile. GENERATED by scripts/gh-project.sh (issue #148): edit the spec
# there, not this output. Needs gh >= 2.30 and jq.
set -euo pipefail

OWNER="$PROJECT_OWNER"
TITLE="$PROJECT_TITLE"
STAGE_FIELD="$STAGE_FIELD"
STAGE_OPTIONS="$STAGE_OPTIONS"
POINTS_FIELD="$POINTS_FIELD"
EOF
  cat <<'EOF'

# 0. `gh project` needs the `project` scope (not granted at login; not covered
#    by a contents:write PAT). `gh auth refresh` manages STORED credentials and
#    ERRORS on a token supplied via GH_TOKEN/GITHUB_TOKEN ("environment variable
#    is being used for authentication") — which under `set -e` would abort this
#    recipe. So only refresh stored creds; with an env-var token (CI/automation)
#    the `project` scope must already be on the token itself.
if [ -n "${GH_TOKEN:-}" ] || [ -n "${GITHUB_TOKEN:-}" ]; then
  echo "auth: using a token from the environment — ensure it carries the 'project' scope" >&2
else
  gh auth refresh -s project
fi

# 1. Board — create only if one with this title does not already exist.
NUM=$(gh project list --owner "$OWNER" -L 200 --format json \
  --jq ".projects[] | select(.title==\"$TITLE\") | .number")
if [ -z "$NUM" ]; then
  gh project create --owner "$OWNER" --title "$TITLE" --format json >/dev/null
  NUM=$(gh project list --owner "$OWNER" -L 200 --format json \
    --jq ".projects[] | select(.title==\"$TITLE\") | .number")
fi
[ -n "$NUM" ] || { echo "could not resolve project number for '$TITLE'" >&2; exit 1; }
echo "project #$NUM  ($TITLE)"

# A field is absent when nothing in the field list has its name (empty result).
field_absent() {  # $1 = field name
  [ -z "$(gh project field-list "$NUM" --owner "$OWNER" -L 200 --format json \
    --jq ".fields[] | select(.name==\"$1\") | .name")" ]
}

# 2. "Story points" (NUMBER) — create if absent.
if field_absent "$POINTS_FIELD"; then
  gh project field-create "$NUM" --owner "$OWNER" --name "$POINTS_FIELD" --data-type NUMBER
  echo "created field: $POINTS_FIELD (NUMBER)"
else
  echo "field exists: $POINTS_FIELD"
fi

# 3. "Stage" (SINGLE_SELECT) with our pipeline options — create if absent.
#    The built-in "Status" field is left untouched (the CLI can't reshape it);
#    group the board's Board view by "Stage" in the UI.
if field_absent "$STAGE_FIELD"; then
  gh project field-create "$NUM" --owner "$OWNER" --name "$STAGE_FIELD" \
    --data-type SINGLE_SELECT --single-select-options "$STAGE_OPTIONS"
  echo "created field: $STAGE_FIELD (SINGLE_SELECT: $STAGE_OPTIONS)"
else
  echo "field exists: $STAGE_FIELD"
fi

echo "done. add issues to the board with:"
echo "  scripts/gh-project.sh add-item https://github.com/$OWNER/print-bench/issues/<N> --stage Backlog --points <n> | bash"
EOF
}

# Emit an idempotent recipe that adds ONE issue/PR to the board and (optionally)
# sets its Stage and Story points. Same emit-only design as emit_recipe: it only
# prints, so it needs no `gh` and is testable. Args: url, stage (may be ""),
# points (may be ""). The caller validates them (add_item_cli) before they are
# substituted here.
emit_add_item() {
  local url="$1" stage="$2" points="$3"
  cat <<EOF
#!/usr/bin/env bash
# Add $url to the "$PROJECT_TITLE" board and set its fields. Idempotent — re-run
# to reconcile. GENERATED by scripts/gh-project.sh (issue #148). Needs gh + jq.
set -euo pipefail

OWNER="$PROJECT_OWNER"
TITLE="$PROJECT_TITLE"
URL="$url"
STAGE="$stage"
POINTS="$points"
STAGE_FIELD="$STAGE_FIELD"
POINTS_FIELD="$POINTS_FIELD"
EOF
  cat <<'EOF'

# Same env-var-token guard as the provisioning recipe (don't abort under set -e).
if [ -n "${GH_TOKEN:-}" ] || [ -n "${GITHUB_TOKEN:-}" ]; then
  echo "auth: using a token from the environment — ensure it carries the 'project' scope" >&2
else
  gh auth refresh -s project
fi

# The board must already exist — run `scripts/gh-project.sh setup | bash` first.
NUM=$(gh project list --owner "$OWNER" -L 200 --format json \
  --jq ".projects[] | select(.title==\"$TITLE\") | .number")
[ -n "$NUM" ] || { echo "board '$TITLE' not found — run: scripts/gh-project.sh setup | bash" >&2; exit 1; }
PID=$(gh project list --owner "$OWNER" -L 200 --format json \
  --jq ".projects[] | select(.title==\"$TITLE\") | .id")

# Idempotent add: reuse the existing board item if this URL is already on the
# board, otherwise add it. (item-add on an already-added URL can duplicate, so
# we look it up first.)
ITEM=$(gh project item-list "$NUM" --owner "$OWNER" -L 500 --format json \
  --jq ".items[] | select(.content.url==\"$URL\") | .id")
if [ -z "$ITEM" ]; then
  ITEM=$(gh project item-add "$NUM" --owner "$OWNER" --url "$URL" --format json --jq '.id')
fi
[ -n "$ITEM" ] || { echo "could not add or find a board item for $URL" >&2; exit 1; }
echo "item $ITEM  ($URL)"

# Stage (single-select): resolve the field id and the option id for this stage.
if [ -n "$STAGE" ]; then
  SF=$(gh project field-list "$NUM" --owner "$OWNER" -L 200 --format json \
    --jq ".fields[] | select(.name==\"$STAGE_FIELD\") | .id")
  OPT=$(gh project field-list "$NUM" --owner "$OWNER" -L 200 --format json \
    --jq ".fields[] | select(.name==\"$STAGE_FIELD\") | .options[] | select(.name==\"$STAGE\") | .id")
  [ -n "$OPT" ] || { echo "stage '$STAGE' is not an option of '$STAGE_FIELD'" >&2; exit 1; }
  gh project item-edit --id "$ITEM" --project-id "$PID" --field-id "$SF" --single-select-option-id "$OPT"
  echo "set $STAGE_FIELD = $STAGE"
fi

# Story points (number).
if [ -n "$POINTS" ]; then
  PF=$(gh project field-list "$NUM" --owner "$OWNER" -L 200 --format json \
    --jq ".fields[] | select(.name==\"$POINTS_FIELD\") | .id")
  gh project item-edit --id "$ITEM" --project-id "$PID" --field-id "$PF" --number "$POINTS"
  echo "set $POINTS_FIELD = $POINTS"
fi
EOF
}

# Parse + VALIDATE the add-item args, then emit the recipe. Validation matters
# because the values are substituted into the emitted recipe: the URL must be a
# real github issue/PR URL, the stage must be one the board actually has, and
# points must be numeric.
add_item_cli() {
  local url="" stage="" points=""
  while [ $# -gt 0 ]; do
    case "$1" in
      --stage)  [ $# -ge 2 ] || die "--stage requires a value";  stage="$2";  shift 2 ;;
      --points) [ $# -ge 2 ] || die "--points requires a value"; points="$2"; shift 2 ;;
      --*)      die "add-item: unknown flag '$1'" ;;
      *)        [ -z "$url" ] || die "add-item: unexpected extra argument '$1'"; url="$1"; shift ;;
    esac
  done
  [ -n "$url" ] || die "add-item: an issue/PR URL is required"
  case "$url" in
    https://github.com/*/*/issues/[0-9]*|https://github.com/*/*/pull/[0-9]*) ;;
    *) die "add-item: '$url' is not a github issue/PR URL" ;;
  esac
  if [ -n "$stage" ]; then
    case ",$STAGE_OPTIONS," in
      *",$stage,"*) ;;
      *) die "add-item: stage '$stage' is not one of: $STAGE_OPTIONS" ;;
    esac
  fi
  if [ -n "$points" ]; then
    case "$points" in ''|*[!0-9]*) die "add-item: --points must be a non-negative integer" ;; esac
  fi
  emit_add_item "$url" "$stage" "$points"
}

selftest() {
  local out
  out="$(emit_recipe)"
  [ -n "$out" ] || die "selftest: emitted an empty recipe"
  # The generated recipe must be valid, runnable bash (syntax-only check).
  bash -n <(printf '%s\n' "$out") || die "selftest: emitted recipe is not valid bash"
  # Spec substitution reached the recipe.
  grep -qF 'TITLE="print-bench autonomy"' <<<"$out" || die "selftest: project title not substituted"
  grep -qF 'OWNER="shaiss"' <<<"$out"               || die "selftest: owner not substituted"
  # The three provisioning steps are present with the verified gh syntax.
  grep -qF 'gh project create --owner "$OWNER" --title "$TITLE"' <<<"$out" \
    || die "selftest: board-create command missing"
  grep -qFe '--data-type NUMBER' <<<"$out"        || die "selftest: Story points NUMBER field missing"
  grep -qFe '--data-type SINGLE_SELECT' <<<"$out" || die "selftest: Stage single-select field missing"
  grep -qF 'Backlog,Ready,In progress,In review,Done' <<<"$out" \
    || die "selftest: stage options missing"
  grep -qF 'gh auth refresh -s project' <<<"$out" || die "selftest: project-scope refresh missing"
  # The refresh must be guarded so an env-var token (CI/automation) doesn't abort
  # the recipe under set -e (Vercel agent review on #164).
  grep -qF 'GH_TOKEN:-' <<<"$out" || die "selftest: env-token auth guard missing"
  # Idempotency guards are present (create-if-absent, not unconditional create).
  grep -qF 'if [ -z "$NUM" ]' <<<"$out" || die "selftest: board create is not guarded (not idempotent)"
  grep -qF 'field_absent' <<<"$out"     || die "selftest: field creates are not guarded (not idempotent)"
  # Negative control: a spec with an empty title must NOT emit a valid create —
  # proves the assertions above are actually checking substituted content.
  local saved="$PROJECT_TITLE" bad
  PROJECT_TITLE=""
  bad="$(emit_recipe)"
  PROJECT_TITLE="$saved"
  if grep -qF 'TITLE="print-bench autonomy"' <<<"$bad"; then
    die "selftest: title substitution is not spec-driven (negative control failed)"
  fi

  # ---- add-item: emit a valid, spec-driven, idempotent recipe --------------
  local add
  add="$("$SELF" add-item "https://github.com/shaiss/print-bench/issues/148" --stage Backlog --points 3)"
  bash -n <(printf '%s\n' "$add") || die "selftest: add-item recipe is not valid bash"
  grep -qF 'URL="https://github.com/shaiss/print-bench/issues/148"' <<<"$add" || die "selftest: add-item url not substituted"
  grep -qF 'STAGE="Backlog"' <<<"$add" || die "selftest: add-item stage not substituted"
  grep -qF 'POINTS="3"' <<<"$add"      || die "selftest: add-item points not substituted"
  grep -qF 'gh project item-add' <<<"$add"    || die "selftest: add-item item-add missing"
  grep -qF 'select(.content.url==' <<<"$add"  || die "selftest: add-item idempotent url lookup missing"
  grep -qFe '--single-select-option-id' <<<"$add" || die "selftest: add-item stage set missing"
  grep -qFe '--number "$POINTS"' <<<"$add"        || die "selftest: add-item points set missing"
  # Negative controls (validation via the real CLI): a bad URL, an unknown
  # stage, and non-numeric points must each be refused before anything runs.
  "$SELF" add-item "not-a-url" >/dev/null 2>&1 \
    && die "selftest: add-item accepted a non-URL" || true
  "$SELF" add-item "https://github.com/shaiss/print-bench/issues/1" --stage Nope >/dev/null 2>&1 \
    && die "selftest: add-item accepted an unknown stage" || true
  "$SELF" add-item "https://github.com/shaiss/print-bench/issues/1" --points x >/dev/null 2>&1 \
    && die "selftest: add-item accepted non-numeric points" || true

  echo "ok    gh-project.sh selftest passed"
}

case "${1:-}" in
  setup)         emit_recipe ;;
  add-item)      shift; add_item_cli "$@" ;;
  --selftest)    selftest ;;
  -h|--help|"")  grep '^#' "$SELF" | sed 's/^# \{0,1\}//' ;;
  *)             die "unknown argument: '$1' (try: setup | add-item | --selftest | --help)" ;;
esac
