#!/usr/bin/env python3
"""growth_mcp.py — Lark's posting surface (Twitter/X), as a stdio MCP tool.

WHY AN MCP TOOL (the same dead end the scout hit)
-------------------------------------------------
Lark's only write is "post ONE queued item to the channel" — and even the
dry-run form of that is rich multi-line markdown (the rendered tweet, a
thread, a table of weights) landing as an issue comment. Under
`--permission-mode dontAsk` the Bash matcher denies any command whose
argument reads as shell structure — an embedded newline is enough, no
quoting fixes it (scout_mcp.py's header has the proof). A JSON tool argument
never touches a command line. Same pattern, the channel-facing consumer.

SECURITY (this tool can reach OUTSIDE the repo — the most-guarded write here)
-----------------------------------------------------------------------------
A live call publishes text to the public internet under the bench's name,
composed by a model that just read UNTRUSTED queue-issue text. So this
server trusts nothing and layers every gate the desk has:

  * DRY-RUN IS THE DEFAULT. A live post happens only when the human live key
    (`GROWTH_TWITTER_LIVE` == 'true', a repo variable no agent can set) AND
    all four X credentials are present. Anything less → the would-be tweet
    lands as a comment on the queue issue, which is the designed deliverable
    for review, not a degraded failure.
  * HUMAN APPROVAL PER ITEM. In live mode (unless the committed policy says
    `require_approval: false`, surfaced as GROWTH_REQUIRE_APPROVAL) the
    queue issue must carry the `approved-to-post` label — a label only a
    human applies; this tool applies NO labels at all.
  * WRITE-TIME TARGET RE-READ. The tool refuses unless the issue is open,
    not a PR, labeled `growth-queue` AND `channel:twitter`, and not parked
    `needs-decision` — a prompt-injected number cannot reach anything else.
  * CANDIDATE BINDING. When the trusted workflow Select step exports
    `GROWTH_SELECTED_ISSUES`, any number outside that set is refused.
  * ONE POST PER QUEUE ITEM, EVER. A hidden marker comment records each
    outcome; a `posted` marker refuses forever, a `dry-run` marker refuses
    further dry-runs (the daily sweep is idempotent) while still allowing
    the eventual approved live post.
  * WEIGHTED LENGTH. Copy is metered with the same rule tools/growth ships
    (URLs = 23, wide code points = 2, hard cap 280 — the parity test pins
    the two implementations together); an over-weight tweet is refused, so
    an unpostable draft can never burn the approval.
  * PER-RUN CAP. `GROWTH_MAX_POSTS` (default 1) bounds an unattended run.
  * The GitHub writes are: the outcome comment, and — after a LIVE post
    only — closing the drained queue issue (queue semantics: the message
    was delivered). Never a label, never another repo, never code.

The OAuth 1.0a mechanics live in the tested tools/growth package
(growth.poster) — imported lazily, ONLY on the live path, from this same
checkout (a committed repo path added to sys.path; not a pip install, so the
stdlib-only rule for the unattended run holds: dry-run touches none of it).
Logs go to stderr so stdout carries nothing but JSON-RPC.
"""

import json
import os
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

QUEUE_LABEL = "growth-queue"
CHANNEL_LABEL = "channel:twitter"
APPROVAL_LABEL = "approved-to-post"
PARKED_LABEL = "needs-decision"
POSTED_MARKER = "<!-- growth-twitter:posted -->"
DRYRUN_MARKER = "<!-- growth-twitter:dry-run -->"
DRYRUN_HEADER = "## \U0001F426 Growth dry run — what Lark would have posted"
POSTED_HEADER = "## \U0001F426 Posted to Twitter/X"
FOOTER = "---\n_Generated by [Claude Code](https://claude.ai/code)_"
GITHUB_API = "https://api.github.com"
SERVER_NAME = "growth_twitter"
DEFAULT_PROTOCOL_VERSION = "2024-11-05"
MAX_THREAD_PARTS = 4

# --- the weighted length rule (self-contained copy) --------------------------
# tools/growth/src/growth/tweetlen.py is the reference implementation; this
# copy exists because the unattended server imports nothing beyond stdlib on
# the dry-run path. tools/growth/tests/test_server_parity.py pins the two
# together on a vector set, so a drift here fails CI.

MAX_WEIGHT = 280
_URL_RE = re.compile(r"https?://\S+")
_WEIGHT_ONE_RANGES = (
    (0x0000, 0x10FF),
    (0x2000, 0x200D),
    (0x2010, 0x201F),
    (0x2032, 0x2037),
)


def _char_weight(cp):
    for lo, hi in _WEIGHT_ONE_RANGES:
        if lo <= cp <= hi:
            return 1
    return 2


def _tweet_weight(text):
    total = 0
    last = 0
    for m in _URL_RE.finditer(text):
        for ch in text[last:m.start()]:
            total += _char_weight(ord(ch))
        total += 23
        last = m.end()
    for ch in text[last:]:
        total += _char_weight(ord(ch))
    return total


# --- run state ---------------------------------------------------------------

# Per-run cap. GITHUB_RUN_ID is set and stable across one Actions run and
# this process lives for that whole run, so an in-process counter is
# naturally run-scoped. Attended (no run id) the cap is skipped — a human is
# the trust boundary, the same posture the sibling servers take.
_posted_this_run = 0

# Captured by the selftest so it can assert exact payloads without a network
# call. `None`/empty in normal operation.
_last_comment = None
_last_close = None
_last_tweets = None

# Fake state for the offline selftest (GROWTH_MCP_FAKE).
_FAKE_ISSUES = {}
_FAKE_COMMENTS = {}


def log(msg):
    """Diagnostics go to stderr — stdout is reserved for JSON-RPC frames."""
    print(f"growth_mcp: {msg}", file=sys.stderr, flush=True)


def _repo():
    repo = os.environ.get("GITHUB_REPOSITORY", "").strip()
    if not repo:
        raise RuntimeError("GITHUB_REPOSITORY is not set")
    return repo


def _token():
    for var in ("GITHUB_TOKEN", "GH_TOKEN"):
        tok = os.environ.get(var, "").strip()
        if tok:
            return tok
    raise RuntimeError("no GitHub token (set GITHUB_TOKEN)")


def _api(method, path, payload=None):
    """One authenticated GitHub REST call. Returns the decoded JSON body."""
    url = f"{GITHUB_API}{path}"
    data = json.dumps(payload).encode() if payload is not None else None
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header("Authorization", f"Bearer {_token()}")
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("X-GitHub-Api-Version", "2022-11-28")
    req.add_header("User-Agent", "print-bench-growth-twitter")
    if data is not None:
        req.add_header("Content-Type", "application/json")
    with urllib.request.urlopen(req, timeout=30) as resp:
        raw = resp.read().decode()
    return json.loads(raw) if raw else {}


def _get_issue(number):
    if os.environ.get("GROWTH_MCP_FAKE"):
        return _FAKE_ISSUES.get(number)
    return _api("GET", f"/repos/{_repo()}/issues/{number}")


def _get_comments(number):
    if os.environ.get("GROWTH_MCP_FAKE"):
        return list(_FAKE_COMMENTS.get(number, []))
    # Walk EVERY page — the marker guard must see an early comment on a long
    # thread, or a duplicate slips through (the assessor's lesson).
    out = []
    page = 1
    while True:
        batch = _api(
            "GET",
            f"/repos/{_repo()}/issues/{number}/comments?per_page=100&page={page}",
        )
        if not isinstance(batch, list) or not batch:
            break
        out.extend(batch)
        if len(batch) < 100:
            break
        page += 1
        if page > 50:  # bound the walk; a queue thread is never this long
            break
    return out


def _post_comment(number, body):
    global _last_comment
    if os.environ.get("GROWTH_MCP_FAKE"):
        if os.environ.get("GROWTH_MCP_FAKE_COMMENT_FAIL"):
            raise RuntimeError("selftest: simulated comment failure")
        _last_comment = {"number": number, "body": body}
        _FAKE_COMMENTS.setdefault(number, []).append({"body": body})
        return {"html_url": f"https://example.invalid/{number}#comment", "id": 0}
    _last_comment = {"number": number, "body": body}
    return _api("POST", f"/repos/{_repo()}/issues/{number}/comments", {"body": body})


def _close_issue(number):
    """Close a DRAINED queue item (live post delivered). The one non-comment
    GitHub write, hardcoded to close-as-completed — never a label."""
    global _last_close
    _last_close = number
    if os.environ.get("GROWTH_MCP_FAKE"):
        return {}
    return _api("PATCH", f"/repos/{_repo()}/issues/{number}",
                {"state": "closed", "state_reason": "completed"})


def _x_post(text, reply_to=None):
    """One live tweet, via the tested OAuth seam in tools/growth (this same
    checkout — see the header). Reached ONLY in live mode."""
    global _last_tweets
    if _last_tweets is None:
        _last_tweets = []
    if os.environ.get("GROWTH_MCP_FAKE"):
        if os.environ.get("GROWTH_MCP_FAKE_X_FAIL"):
            raise RuntimeError("selftest: simulated X API failure")
        _last_tweets.append({"text": text, "reply_to": reply_to})
        return f"fake-tweet-{len(_last_tweets)}"
    repo_root = Path(__file__).resolve().parents[3]
    sys.path.insert(0, str(repo_root / "tools" / "growth" / "src"))
    from growth.poster import post_tweet as poster_post_tweet  # noqa: PLC0415
    return poster_post_tweet(text, reply_to=reply_to)


def _selected_issues():
    """The trusted workflow Select step exports GROWTH_SELECTED_ISSUES (space-
    or comma-separated digits) — the run's candidate set. Returns a set, or
    None when unset (attended: a human is the trust boundary, no binding)."""
    raw = os.environ.get("GROWTH_SELECTED_ISSUES", "").strip()
    if not raw:
        return None
    nums = set()
    for tok in raw.replace(",", " ").split():
        if tok.isdigit():
            nums.add(int(tok))
    return nums


def _label_names(issue):
    out = []
    for lbl in (issue.get("labels") or []):
        out.append(lbl.get("name", "") if isinstance(lbl, dict) else str(lbl))
    return out


def _x_credentials_present():
    return all(
        (os.environ.get(v) or "").strip()
        for v in ("X_API_KEY", "X_API_SECRET", "X_ACCESS_TOKEN", "X_ACCESS_TOKEN_SECRET")
    )


def _live_mode():
    """Live iff the human live key says so AND the channel credentials exist.
    Everything else — including 'keys arrived but nobody flipped the
    variable' — is a dry run. The variable is a repo variable exported by the
    workflow; no agent can set it."""
    return (
        os.environ.get("GROWTH_TWITTER_LIVE", "").strip() == "true"
        and _x_credentials_present()
    )


def _require_approval():
    """The committed policy's require_approval, surfaced by the workflow as
    GROWTH_REQUIRE_APPROVAL. Fail-safe: anything but the literal 'false'
    means approval is required."""
    return os.environ.get("GROWTH_REQUIRE_APPROVAL", "true").strip() != "false"


def _render_parts(text, thread):
    parts = [text] + list(thread)
    lines = []
    for i, part in enumerate(parts, start=1):
        prefix = f"**{i}/{len(parts)}**\n" if len(parts) > 1 else ""
        quoted = "> " + part.replace("\n", "\n> ")
        lines.append(f"{prefix}{quoted}\n({_tweet_weight(part)}/{MAX_WEIGHT} weighted)")
    return "\n\n".join(lines)


def _post_tweet(arguments):
    """Drain ONE queue item to the channel — dry-run comment by default, a
    live tweet only behind the live key + approval label. Lark's entire
    write taxonomy."""
    global _posted_this_run
    args = arguments or {}
    number = args.get("number")
    text = args.get("text")
    thread = args.get("thread") or []

    # --- input shape -------------------------------------------------------
    if isinstance(number, bool):
        return _tool_error("post_tweet: 'number' must be an integer issue number")
    if isinstance(number, str):
        if not number.strip().isdigit():
            return _tool_error(
                f"post_tweet: 'number' must be a positive integer (got {number!r})")
        number = int(number.strip())
    if not isinstance(number, int) or number <= 0:
        return _tool_error("post_tweet: 'number' is required (positive integer)")
    if not isinstance(text, str) or not text.strip():
        return _tool_error("post_tweet: 'text' is required (non-empty string)")
    if not isinstance(thread, list) or any(
            not isinstance(p, str) or not p.strip() for p in thread):
        return _tool_error("post_tweet: 'thread' must be a list of non-empty strings")
    if len(thread) > MAX_THREAD_PARTS:
        return _tool_error(
            f"post_tweet: a thread carries at most {MAX_THREAD_PARTS} follow-ups "
            f"(got {len(thread)}) — one idea per post; condense")

    # --- weighted length, every part ---------------------------------------
    for i, part in enumerate([text, *thread]):
        w = _tweet_weight(part)
        if w > MAX_WEIGHT:
            where = "text" if i == 0 else f"thread[{i - 1}]"
            return _tool_error(
                f"post_tweet: {where} is {w} weighted (cap {MAX_WEIGHT}; URLs "
                f"count 23, wide code points 2) — shorten it")

    # --- candidate-set binding (trusted Select step) -----------------------
    selected = _selected_issues()
    if selected is not None and number not in selected:
        return _tool_error(
            f"issue #{number} is not in this run's candidate set {sorted(selected)}; refusing")

    # --- per-run cap (unattended only) -------------------------------------
    if os.environ.get("GITHUB_RUN_ID", "").strip():
        try:
            cap = int(os.environ.get("GROWTH_MAX_POSTS", "1"))
        except ValueError:
            cap = 1
        if _posted_this_run >= cap:
            return _tool_error(
                f"per-run post cap reached ({_posted_this_run}/{cap}); refusing to post more")

    # --- re-read the target and enforce state at WRITE time ----------------
    try:
        issue = _get_issue(number)
    except urllib.error.HTTPError as e:
        return _tool_error(f"GitHub API error {e.code} reading issue #{number}")
    except Exception as e:  # noqa: BLE001 — surface any failure to the agent
        return _tool_error(f"failed to read issue #{number}: {type(e).__name__}: {e}")
    if not issue:
        return _tool_error(f"issue #{number} not found")
    if "pull_request" in issue:
        return _tool_error(f"#{number} is a pull request, not a queue item; refusing")
    if issue.get("state") != "open":
        return _tool_error(f"issue #{number} is not open (state={issue.get('state')!r}); refusing")
    labels = _label_names(issue)
    if QUEUE_LABEL not in labels:
        return _tool_error(f"issue #{number} does not carry the '{QUEUE_LABEL}' label; refusing")
    if CHANNEL_LABEL not in labels:
        return _tool_error(
            f"issue #{number} is not this channel's ('{CHANNEL_LABEL}' label missing); refusing")
    if PARKED_LABEL in labels:
        return _tool_error(
            f"issue #{number} is parked for a human ('{PARKED_LABEL}'); refusing")

    live = _live_mode()

    # --- approval gate (live only) -----------------------------------------
    if live and _require_approval() and APPROVAL_LABEL not in labels:
        return _tool_error(
            f"issue #{number} lacks the '{APPROVAL_LABEL}' label — a human "
            f"approves each live post (the dry-run comment is there to "
            f"review); refusing the live post")

    # --- marker guards — one post per queue item, ever ---------------------
    try:
        comments = _get_comments(number)
    except Exception as e:  # noqa: BLE001
        return _tool_error(f"failed to read comments on #{number}: {type(e).__name__}: {e}")
    bodies = [(c.get("body") or "") for c in comments]
    if any(POSTED_MARKER in b for b in bodies):
        return _tool_error(f"issue #{number} was already posted live; refusing a duplicate")
    if not live and any(DRYRUN_MARKER in b for b in bodies):
        return _tool_error(
            f"issue #{number} already carries a dry-run comment; refusing a "
            f"duplicate (a later approved LIVE post is still allowed)")

    # --- act ----------------------------------------------------------------
    rendered = _render_parts(text, thread)
    if live:
        # CLAIM FIRST, POST SECOND. The posted marker is the only cross-run
        # dedup signal, so it must exist even if this run dies mid-post: a
        # claim written before the first tweet turns every partial failure
        # into at-worst a LOST post a human retries deliberately — never a
        # DUPLICATE on a public channel. (If the claim itself cannot be
        # written, nothing has been published yet, so refusing is free.)
        claim = (
            f"{POSTED_MARKER}\n{POSTED_HEADER}\n\n_Live posting in flight — if no"
            f" tweet URL follows in a later comment, verify on the channel"
            f" before re-queuing; this item will not be posted again._\n\n"
            f"{rendered}\n\n{FOOTER}"
        )
        try:
            _post_comment(number, claim)
        except Exception as e:  # noqa: BLE001
            return _tool_error(
                f"could not claim #{number} before posting "
                f"({type(e).__name__}: {e}) — nothing was published; retry next run")
        try:
            first_id = _x_post(text)
            last_id = first_id
            for part in thread:
                last_id = _x_post(part, reply_to=last_id)
        except Exception as e:  # noqa: BLE001
            # The claim marker is already on the issue, so no later run can
            # double-post; a human verifies what (if anything) reached the
            # channel and re-queues a fresh item if needed.
            _posted_this_run += 1
            return _tool_error(
                f"live post for #{number} failed mid-flight "
                f"({type(e).__name__}: {e}) — the item is claim-marked and "
                f"will not be retried automatically; verify the channel by hand")
        tweet_url = f"https://x.com/i/web/status/{first_id}"
        comment = f"{POSTED_HEADER}\n\n{tweet_url}\n\nQueue item drained — closing.\n\n{FOOTER}"
        try:
            _post_comment(number, comment)
            _close_issue(number)
        except Exception as e:  # noqa: BLE001
            # The tweet is out and the claim marker already guards against a
            # re-post; surface the bookkeeping failure loudly.
            _posted_this_run += 1
            return _tool_error(
                f"tweet posted ({tweet_url}) but recording it on #{number} "
                f"failed: {type(e).__name__}: {e} — close the item by hand")
        _posted_this_run += 1
        log(f"posted live for #{number}: {tweet_url}")
        return _tool_text(f"POSTED live for #{number} {tweet_url} (queue item closed)")

    reasons = []
    if os.environ.get("GROWTH_TWITTER_LIVE", "").strip() != "true":
        reasons.append("the `GROWTH_TWITTER_LIVE` repo variable is not 'true'")
    if not _x_credentials_present():
        reasons.append("the X credentials are not configured")
    if _require_approval() and APPROVAL_LABEL not in labels:
        reasons.append(f"the `{APPROVAL_LABEL}` label is not applied")
    comment = (
        f"{DRYRUN_MARKER}\n{DRYRUN_HEADER}\n\n{rendered}\n\n"
        f"**Dry run** — nothing was published. Going live needs: "
        f"{'; '.join(reasons) if reasons else 'nothing further'}. "
        f"See docs/growth.md.\n\n{FOOTER}"
    )
    try:
        posted = _post_comment(number, comment)
    except urllib.error.HTTPError as e:
        detail = e.read().decode(errors="replace")[:500] if hasattr(e, "read") else ""
        return _tool_error(f"GitHub API error {e.code} commenting on #{number}: {detail}")
    except Exception as e:  # noqa: BLE001
        return _tool_error(f"failed to comment on #{number}: {type(e).__name__}: {e}")
    _posted_this_run += 1
    url = posted.get("html_url", "(unknown url)")
    log(f"dry-ran #{number} {url} ({_posted_this_run} this run)")
    return _tool_text(f"DRY-RUN recorded on #{number} {url}")


# --- MCP tool registry ------------------------------------------------------

TOOLS = [
    {
        "name": "post_tweet",
        "description": (
            "Drain ONE growth-queue item to Twitter/X. Pass the queue issue "
            "'number', the tweet 'text', and optionally 'thread' (up to 4 "
            "follow-up tweets). Copy is metered with the weighted rule (URLs "
            "= 23, cap 280). By default this is a DRY RUN: the would-be tweet "
            "is recorded as a comment on the queue issue for a human to "
            "review — that comment is the deliverable. A LIVE post happens "
            "only when the human live key and X credentials are configured "
            "AND (per policy) the issue carries the approved-to-post label; "
            "after a live post the drained issue is closed. The tool re-reads "
            "the target and refuses anything that is not an open, "
            "twitter-channel queue item; one post per item, ever. A refusal "
            "is final — fix what it names or move on, never retry unchanged."
        ),
        "inputSchema": {
            "type": "object",
            "properties": {
                "number": {
                    "type": "integer",
                    "description": "The growth-queue issue number being drained.",
                },
                "text": {
                    "type": "string",
                    "description": "The tweet (weighted length ≤ 280; compose to ≤ 270).",
                },
                "thread": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Optional follow-up tweets (max 4), posted as replies.",
                },
            },
            "required": ["number", "text"],
            "additionalProperties": False,
        },
    }
]

_DISPATCH = {"post_tweet": _post_tweet}


def _tool_text(text):
    return {"content": [{"type": "text", "text": text}], "isError": False}


def _tool_error(text):
    log(text)
    return {"content": [{"type": "text", "text": f"Error: {text}"}], "isError": True}


# --- JSON-RPC over stdio (newline-delimited) --------------------------------

def _result(msg_id, result):
    return {"jsonrpc": "2.0", "id": msg_id, "result": result}


def _error(msg_id, code, message):
    return {"jsonrpc": "2.0", "id": msg_id, "error": {"code": code, "message": message}}


def handle(msg):
    """Map one JSON-RPC request to a response dict, or None for notifications."""
    method = msg.get("method")
    msg_id = msg.get("id")

    if msg_id is None and "id" not in msg:
        # Notifications (no id) get no response.
        return None

    if method == "initialize":
        params = msg.get("params") or {}
        version = params.get("protocolVersion") or DEFAULT_PROTOCOL_VERSION
        return _result(
            msg_id,
            {
                "protocolVersion": version,
                "capabilities": {"tools": {}},
                "serverInfo": {"name": SERVER_NAME, "version": "1.0.0"},
            },
        )

    if method == "ping":
        return _result(msg_id, {})

    if method == "tools/list":
        return _result(msg_id, {"tools": TOOLS})

    if method == "tools/call":
        params = msg.get("params") or {}
        name = params.get("name")
        fn = _DISPATCH.get(name)
        if fn is None:
            return _result(msg_id, _tool_error(f"unknown tool: {name!r}"))
        return _result(msg_id, fn(params.get("arguments") or {}))

    return _error(msg_id, -32601, f"method not found: {method}")


def selftest():
    """Prove the write surface's security invariants fire, offline. A guard
    that is never exercised can be weakened and every other check stays green
    (the repo's standing rule) — and THIS surface can reach outside the repo,
    so these are the cases that must never regress."""
    global _posted_this_run, _last_comment, _last_close, _last_tweets
    global _FAKE_ISSUES, _FAKE_COMMENTS
    os.environ["GROWTH_MCP_FAKE"] = "1"
    for var in ("GROWTH_SELECTED_ISSUES", "GITHUB_RUN_ID", "GROWTH_TWITTER_LIVE",
                "GROWTH_REQUIRE_APPROVAL", "GROWTH_MAX_POSTS",
                "X_API_KEY", "X_API_SECRET", "X_ACCESS_TOKEN", "X_ACCESS_TOKEN_SECRET"):
        os.environ.pop(var, None)
    fails = []

    def check(name, cond):
        print(f"{'ok  ' if cond else 'FAIL'}  {name}")
        if not cond:
            fails.append(name)

    def err(res):
        return res.get("isError") is True

    def q(number, labels, state="open", pr=False):
        issue = {"number": number, "state": state,
                 "labels": [{"name": n} for n in labels]}
        if pr:
            issue["pull_request"] = {"url": "x"}
        return issue

    OK = [QUEUE_LABEL, CHANNEL_LABEL]
    _FAKE_ISSUES = {
        1: q(1, OK),
        2: q(2, OK, state="closed"),
        3: q(3, [CHANNEL_LABEL]),
        4: q(4, [QUEUE_LABEL]),
        5: q(5, OK + [PARKED_LABEL]),
        6: q(6, OK, pr=True),
        7: q(7, OK),
        8: q(8, OK),
        9: q(9, OK),
        10: q(10, OK + [APPROVAL_LABEL]),
        11: q(11, OK),
        12: q(12, OK + [APPROVAL_LABEL]),
    }
    _FAKE_COMMENTS = {
        7: [{"body": f"{POSTED_MARKER}\nposted earlier"}],
        8: [{"body": f"{DRYRUN_MARKER}\ndry-ran earlier"}],
        12: [{"body": f"{DRYRUN_MARKER}\ndry-ran earlier"}],
    }

    # Input guards.
    check("missing number is rejected", err(_post_tweet({"text": "x"})))
    check("a boolean number is rejected (bool is an int subclass)",
          err(_post_tweet({"number": True, "text": "x"})))
    check("a non-numeric number is rejected",
          err(_post_tweet({"number": "abc", "text": "x"})))
    check("missing text is rejected", err(_post_tweet({"number": 1})))
    check("a non-list thread is rejected",
          err(_post_tweet({"number": 1, "text": "x", "thread": "y"})))
    check("an empty thread part is rejected",
          err(_post_tweet({"number": 1, "text": "x", "thread": ["ok", "  "]})))
    check("a thread over 4 parts is rejected",
          err(_post_tweet({"number": 1, "text": "x", "thread": list("abcde")})))

    # Weighted length — URLs count 23, so a 2000-char URL passes and 281
    # plain chars fail; the guard covers thread parts too.
    check("281 plain chars are rejected",
          err(_post_tweet({"number": 1, "text": "x" * 281})))
    long_url = "https://example.com/" + "p" * 2000
    r = _post_tweet({"number": 1, "text": f"ok {long_url}"})
    check("a long URL weighs 23 and passes", r.get("isError") is False)
    _FAKE_COMMENTS.pop(1, None)  # reset the dry-run marker that call left
    check("an over-weight thread part is rejected",
          err(_post_tweet({"number": 1, "text": "ok", "thread": ["y" * 281]})))

    # Dry-run is the default: no live key, no creds → the comment carries the
    # dry-run marker, the header, the footer, and the issue is NOT closed.
    _last_comment, _last_close = None, None
    r = _post_tweet({"number": 9, "text": "hello bench",
                     "thread": ["second part"]})
    check("default mode is dry-run", r.get("isError") is False
          and "DRY-RUN" in r["content"][0]["text"])
    check("the dry-run comment carries the marker",
          _last_comment and _last_comment["body"].startswith(DRYRUN_MARKER))
    check("the dry-run comment carries the attribution footer",
          _last_comment and _last_comment["body"].endswith(FOOTER))
    check("the dry-run comment renders the thread part",
          _last_comment and "second part" in _last_comment["body"])
    check("a dry run never closes the queue item", _last_close is None)

    # State guards at write time.
    check("a closed issue is rejected", err(_post_tweet({"number": 2, "text": "x"})))
    check("a missing growth-queue label is rejected",
          err(_post_tweet({"number": 3, "text": "x"})))
    check("a missing channel:twitter label is rejected",
          err(_post_tweet({"number": 4, "text": "x"})))
    check("a needs-decision item is rejected", err(_post_tweet({"number": 5, "text": "x"})))
    check("a pull request is rejected", err(_post_tweet({"number": 6, "text": "x"})))

    # Marker guards.
    check("an already-posted item is refused",
          err(_post_tweet({"number": 7, "text": "x"})))
    check("a second dry-run on the same item is refused",
          err(_post_tweet({"number": 8, "text": "x"})))

    # Candidate binding.
    os.environ["GROWTH_SELECTED_ISSUES"] = "1"
    check("a number outside the run's candidate set is rejected",
          err(_post_tweet({"number": 9, "text": "x"})))
    os.environ.pop("GROWTH_SELECTED_ISSUES", None)

    # Live mode needs BOTH the human key and the credentials.
    for v in ("X_API_KEY", "X_API_SECRET", "X_ACCESS_TOKEN", "X_ACCESS_TOKEN_SECRET"):
        os.environ[v] = "cred"
    _last_comment = None
    r = _post_tweet({"number": 11, "text": "creds but no key"})
    check("credentials without the live key still dry-run",
          r.get("isError") is False and DRYRUN_MARKER in _last_comment["body"])

    os.environ["GROWTH_TWITTER_LIVE"] = "true"
    # Live + approval required + label absent → refused.
    check("live mode without the approval label is refused",
          err(_post_tweet({"number": 9, "text": "x"})))
    # Live + approved → claims, posts, records, closes; an earlier dry-run
    # marker does not block the approved live post.
    _last_tweets, _last_close, _last_comment = None, None, None
    r = _post_tweet({"number": 12, "text": "approved and live",
                     "thread": ["part two"]})
    check("an approved item posts live over its old dry-run marker",
          r.get("isError") is False and "POSTED live" in r["content"][0]["text"])
    check("the thread posts as replies in order",
          _last_tweets == [{"text": "approved and live", "reply_to": None},
                           {"text": "part two", "reply_to": "fake-tweet-1"}])
    check("the CLAIM comment carries the posted marker and lands BEFORE the tweets",
          any(c["body"].startswith(POSTED_MARKER) for c in _FAKE_COMMENTS[12]))
    check("the outcome comment carries the tweet URL",
          _last_comment and "https://x.com/i/web/status/" in _last_comment["body"])
    check("a live post closes the drained queue item", _last_close == 12)
    # And a posted item never posts again, in any mode.
    check("a live-posted item is refused forever",
          err(_post_tweet({"number": 12, "text": "again"})))

    # A mid-flight X failure must NOT allow a later duplicate: the claim
    # marker was written before the first tweet, so the retry is refused.
    _FAKE_ISSUES[13] = q(13, OK + [APPROVAL_LABEL])
    os.environ["GROWTH_MCP_FAKE_X_FAIL"] = "1"
    r = _post_tweet({"number": 13, "text": "will fail mid-flight"})
    check("a mid-flight X failure errors loudly",
          err(r) and "claim-marked" in r["content"][0]["text"])
    check("the failed item is claim-marked",
          any(POSTED_MARKER in c["body"] for c in _FAKE_COMMENTS.get(13, [])))
    os.environ.pop("GROWTH_MCP_FAKE_X_FAIL", None)
    check("the claim-marked item is refused on the next attempt (no duplicate)",
          err(_post_tweet({"number": 13, "text": "retry"})))

    # If the claim itself cannot be written, nothing is published.
    _FAKE_ISSUES[14] = q(14, OK + [APPROVAL_LABEL])
    _last_tweets = None
    os.environ["GROWTH_MCP_FAKE_COMMENT_FAIL"] = "1"
    r = _post_tweet({"number": 14, "text": "cannot claim"})
    check("an unclaimable item publishes nothing",
          err(r) and "nothing was published" in r["content"][0]["text"]
          and not _last_tweets)
    os.environ.pop("GROWTH_MCP_FAKE_COMMENT_FAIL", None)

    # The live key without credentials is still a dry run.
    for v in ("X_API_KEY", "X_API_SECRET", "X_ACCESS_TOKEN", "X_ACCESS_TOKEN_SECRET"):
        os.environ.pop(v, None)
    _last_comment = None
    r = _post_tweet({"number": 10, "text": "key but no creds"})
    check("the live key without credentials still dry-runs",
          r.get("isError") is False and DRYRUN_MARKER in _last_comment["body"])
    os.environ.pop("GROWTH_TWITTER_LIVE", None)

    # Per-run cap (unattended: GITHUB_RUN_ID set). Default cap is 1.
    os.environ["GITHUB_RUN_ID"] = "selftest-run"
    _posted_this_run = 0
    _FAKE_ISSUES[20] = q(20, OK)
    _FAKE_ISSUES[21] = q(21, OK)
    r1 = _post_tweet({"number": 20, "text": "one"})
    r2 = _post_tweet({"number": 21, "text": "two"})
    check("the cap lets through GROWTH_MAX_POSTS (default 1)",
          r1.get("isError") is False)
    check("the cap refuses past the limit",
          err(r2) and "cap reached" in r2["content"][0]["text"])
    os.environ.pop("GITHUB_RUN_ID", None)

    # The JSON-RPC surface exposes exactly the one tool.
    check("tools/list exposes exactly post_tweet",
          [t["name"] for t in TOOLS] == ["post_tweet"])

    if fails:
        print(f"\ngrowth_mcp selftest FAILED: {', '.join(fails)}")
        return 1
    print("\ngrowth_mcp selftest passed")
    return 0


def main():
    if "--selftest" in sys.argv:
        raise SystemExit(selftest())
    log(f"starting (repo={os.environ.get('GITHUB_REPOSITORY', '?')}, "
        f"run={os.environ.get('GITHUB_RUN_ID', 'attended')}, "
        f"mode={'LIVE' if _live_mode() else 'dry-run'})")
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            msg = json.loads(line)
        except json.JSONDecodeError as e:
            log(f"skipping unparseable line: {e}")
            continue
        try:
            response = handle(msg)
        except Exception as e:  # noqa: BLE001 — never let one message kill the loop
            log(f"handler error: {type(e).__name__}: {e}")
            response = _error(msg.get("id"), -32603, f"internal error: {e}")
        if response is not None:
            sys.stdout.write(json.dumps(response) + "\n")
            sys.stdout.flush()
    log("stdin closed, exiting")


if __name__ == "__main__":
    main()
